### ISSUE TITLE
localcache 

### ISSUE THREAD

**Issue by OsamaDevo00** [flaviotordini/minitube#100]
just it doesn't work.
![screenshot from 2018-03-06 12 29 08](https://user-images.githubusercontent.com/35396150/37027559-b988dc70-2142-11e8-8ac1-114fe690b1a3.png)

**Comment by flaviotordini** [comment]
You need Qt >= 5.4

**Comment by OsamaDevo00** [comment]
sorry I read the (readme file) after I summit the issue. and thanks for
your correction and I will update my Qt.
