### ISSUE TITLE
2.9 does not work on Linux Mint / Ubuntu LTS

### ISSUE THREAD

**Issue by ginsterbusch** [flaviotordini/minitube#104]
The same issue as with 2.8 appeared: When trying to start minitube, the program aborted with the following error message:

```
minitube: symbol lookup error: minitube: undefined symbol: _ZNK18QAbstractListModel7siblingEiiRK11QModelIndex
```

System: Linux Mint 17.3 / Ubuntu 14.04.5 LTS, x86_64

My current workaround is a downgrade to 2.7.2; de facto the same workaround as for 2.8 (which complained about undefined, but different symbol(s), too).

**Comment by flaviotordini** [comment]
That's probably an older Qt version. Ubuntu 14.04 is too old there is another LTS after that. I build my packages to support the latest Ubuntu LTS.
