### ISSUE TITLE
Compiling error for 2.9 on 32-bit Ubuntu 16.04 

### ISSUE THREAD

**Issue by msalini** [flaviotordini/minitube#105]
Hi there,

I get the following errors when running `make`

 ``build/obj/qtsingleapplication.o: In function `QtSingleApplication::QtSingleApplication(int&, char**, bool)':
qtsingleapplication.cpp:(.text+0x88): undefined reference to `QApplication::QApplication(int&, char**, bool, int)'
qtsingleapplication.cpp:(.text+0x95): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x9c): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0xdf): undefined reference to `QString::free(QString::Data*)'
qtsingleapplication.cpp:(.text+0x103): undefined reference to `QString::free(QString::Data*)'
build/obj/qtsingleapplication.o: In function `QtSingleApplication::QtSingleApplication(int&, char**, QApplication::Type)':
qtsingleapplication.cpp:(.text+0x196): undefined reference to `QApplication::QApplication(int&, char**, QApplication::Type, int)'
qtsingleapplication.cpp:(.text+0x1a3): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x1aa): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x1ef): undefined reference to `QString::free(QString::Data*)'
qtsingleapplication.cpp:(.text+0x213): undefined reference to `QString::free(QString::Data*)'
build/obj/qtsingleapplication.o: In function `QtSingleApplication::QtSingleApplication(_XDisplay*, unsigned long, unsigned long)':
qtsingleapplication.cpp:(.text+0x256): undefined reference to `QApplication::QApplication(_XDisplay*, unsigned long, unsigned long, int)'
qtsingleapplication.cpp:(.text+0x263): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x26a): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x2af): undefined reference to `QString::free(QString::Data*)'
qtsingleapplication.cpp:(.text+0x2d3): undefined reference to `QString::free(QString::Data*)'
build/obj/qtsingleapplication.o: In function `QtSingleApplication::QtSingleApplication(_XDisplay*, int&, char**, unsigned long, unsigned long)':
qtsingleapplication.cpp:(.text+0x31c): undefined reference to `QApplication::QApplication(_XDisplay*, int&, char**, unsigned long, unsigned long, int)'
qtsingleapplication.cpp:(.text+0x329): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x330): undefined reference to `QString::shared_null'
qtsingleapplication.cpp:(.text+0x377): undefined reference to `QString::free(QString::Data*)'
qtsingleapplication.cpp:(.text+0x39b): undefined reference to `QString::free(QString::Data*)'
build/obj/qtsingleapplication.o: In function `QtSingleApplication::QtSingleApplication(_XDisplay*, QString const&, int, char**, unsigned long, unsigned long)':
qtsingleapplication.cpp:(.text+0x3e2): undefined reference to `QApplication::QApplication(_XDisplay*, int&, char**, unsigned long, unsigned long, int)'
build/obj/qtlocalpeer.o: In function `QtLP_Private::QtLockedFile::unlock()':
qtlocalpeer.cpp:(.text+0xde): undefined reference to `QFile::handle() const'
qtlocalpeer.cpp:(.text+0x111): undefined reference to `qWarning(char const*, ...)'
qtlocalpeer.cpp:(.text+0x13a): undefined reference to `qWarning(char const*, ...)'
build/obj/qtlocalpeer.o: In function `QtLP_Private::QtLockedFile::lock(QtLP_Private::QtLockedFile::LockMode, bool)':
qtlocalpeer.cpp:(.text+0x1cb): undefined reference to `QFile::handle() const'
qtlocalpeer.cpp:(.text+0x211): undefined reference to `qWarning(char const*, ...)'
qtlocalpeer.cpp:(.text+0x265): undefined reference to `qWarning(char const*, ...)'
build/obj/qtlocalpeer.o: In function `QtLocalPeer::isClient()':
qtlocalpeer.cpp:(.text+0x3d9): undefined reference to `qWarning(char const*, ...)'
qtlocalpeer.cpp:(.text+0x409): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x467): undefined reference to `QString::realloc()'
qtlocalpeer.cpp:(.text+0x527): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x537): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x547): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x586): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x5a1): undefined reference to `QString::free(QString::Data*)'
build/obj/qtlocalpeer.o:qtlocalpeer.cpp:(.text+0x5cb): more undefined references to `QString::free(QString::Data*)' follow
build/obj/qtlocalpeer.o: In function `QtLP_Private::QtLockedFile::open(QFlags<QIODevice::OpenModeFlag>)':
qtlocalpeer.cpp:(.text+0x691): undefined reference to `qWarning(char const*, ...)'
build/obj/qtlocalpeer.o: In function `QtLocalPeer::QtLocalPeer(QObject*, QString const&)':
qtlocalpeer.cpp:(.text+0x6e7): undefined reference to `QString::shared_null'
qtlocalpeer.cpp:(.text+0x6ee): undefined reference to `QString::shared_null'
qtlocalpeer.cpp:(.text+0x7e8): undefined reference to `QString::shared_null'
qtlocalpeer.cpp:(.text+0x7ef): undefined reference to `QString::shared_null'
qtlocalpeer.cpp:(.text+0x838): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x8b5): undefined reference to `QString::realloc()'
qtlocalpeer.cpp:(.text+0x954): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x99f): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0xa19): undefined reference to `QString::realloc()'
qtlocalpeer.cpp:(.text+0xaad): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0xad4): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0xb4f): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0xb67): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0xb77): undefined reference to `QString::free(QString::Data*)'
build/obj/qtlocalpeer.o:qtlocalpeer.cpp:(.text+0xba7): more undefined references to `QString::free(QString::Data*)' follow
build/obj/qtlocalpeer.o: In function `QtLocalPeer::receiveConnection()':
qtlocalpeer.cpp:(.text+0xfa5): undefined reference to `QByteArray::shared_null'
qtlocalpeer.cpp:(.text+0xfac): undefined reference to `QByteArray::shared_null'
qtlocalpeer.cpp:(.text+0xfe9): undefined reference to `QByteArray::realloc(int)'
qtlocalpeer.cpp:(.text+0x1052): undefined reference to `QString::fromUtf8(char const*, int)'
qtlocalpeer.cpp:(.text+0x1136): undefined reference to `qWarning(char const*, ...)'
qtlocalpeer.cpp:(.text+0x11bc): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x11e2): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x1240): undefined reference to `QString::free(QString::Data*)'
qtlocalpeer.cpp:(.text+0x127e): undefined reference to `QString::free(QString::Data*)'
build/obj/qtlocalpeer.o: In function `QString& operator+=<QLatin1Char, QString>(QString&, QStringBuilder<QLatin1Char, QString> const&)':
qtlocalpeer.cpp:(.text._ZpLI11QLatin1Char7QStringERS1_S2_RK14QStringBuilderIT_T0_E[_ZpLI11QLatin1Char7QStringERS1_S2_RK14QStringBuilderIT_T0_E]+0x2d): undefined reference to `QString::realloc(int)'
qtlocalpeer.cpp:(.text._ZpLI11QLatin1Char7QStringERS1_S2_RK14QStringBuilderIT_T0_E[_ZpLI11QLatin1Char7QStringERS1_S2_RK14QStringBuilderIT_T0_E]+0x46): undefined reference to `QString::realloc()'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x30): undefined reference to `QObject::connectNotify(char const*)'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x34): undefined reference to `QObject::disconnectNotify(char const*)'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x38): undefined reference to `QFile::isSequential() const'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x40): undefined reference to `QFile::close()'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x44): undefined reference to `QFile::pos() const'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x4c): undefined reference to `QFile::seek(long long)'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x50): undefined reference to `QFile::atEnd() const'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x6c): undefined reference to `QFile::readData(char*, long long)'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x70): undefined reference to `QFile::readLineData(char*, long long)'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x74): undefined reference to `QFile::writeData(char const*, long long)'
build/obj/qtlocalpeer.o:(.rodata._ZTVN12QtLP_Private12QtLockedFileE[_ZTVN12QtLP_Private12QtLockedFileE]+0x78): undefined reference to `QFile::fileEngine() const'
build/obj/cachedhttp.o: In function `CachedHttpReply::CachedHttpReply(QByteArray const&, HttpRequest const&)':
cachedhttp.cpp:(.text+0x39): undefined reference to `QTimer::singleShot(int, QObject*, char const*)'
build/obj/cachedhttp.o: In function `CachedHttp::request(HttpRequest const&)':
cachedhttp.cpp:(.text+0x278): undefined reference to `QUrl::toEncoded(QFlags<QUrl::FormattingOption>) const'
cachedhttp.cpp:(.text+0x2c8): undefined reference to `QByteArray::realloc(int)'
build/obj/cachedhttp.o: In function `QMap<QByteArray, QByteArray>::~QMap()':
cachedhttp.cpp:(.text._ZN4QMapI10QByteArrayS0_ED2Ev[_ZN4QMapI10QByteArrayS0_ED5Ev]+0x83): undefined reference to `QMapData::continueFreeData(int)'
build/obj/http.o: In function `QMap<QByteArray, QByteArray>::freeData(QMapData*) [clone .isra.5]':
http.cpp:(.text+0x63): undefined reference to `QMapData::continueFreeData(int)'
build/obj/http.o: In function `QMap<QString, QString>::freeData(QMapData*) [clone .isra.10]':
http.cpp:(.text+0xaa): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0xc1): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0xd3): undefined reference to `QMapData::continueFreeData(int)'
build/obj/http.o: In function `Http::request(QUrl const&, QNetworkAccessManager::Operation, QByteArray const&, unsigned int)':
http.cpp:(.text+0x144): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x14b): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x15c): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0x163): undefined reference to `QMapData::shared_null'
build/obj/http.o: In function `Http::get(QUrl const&)':
http.cpp:(.text+0x25a): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x273): undefined reference to `QByteArray::shared_null'
build/obj/http.o: In function `Http::head(QUrl const&)':
http.cpp:(.text+0x2fa): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x313): undefined reference to `QByteArray::shared_null'
build/obj/http.o: In function `NetworkHttpReply::errorMessage()':
http.cpp:(.text+0x44c): undefined reference to `QUrl::toString(QFlags<QUrl::FormattingOption>) const'
http.cpp:(.text+0x48f): undefined reference to `QString::realloc()'
http.cpp:(.text+0x519): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x54d): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x577): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x5af): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x5ca): undefined reference to `QString::free(QString::Data*)'
build/obj/http.o:http.cpp:(.text+0x5f1): more undefined references to `QString::free(QString::Data*)' follow
build/obj/http.o: In function `Http::addRequestHeader(QByteArray const&, QByteArray const&)':
http.cpp:(.text+0xa73): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
build/obj/http.o: In function `Http::post(QUrl const&, QByteArray const&, QByteArray const&)':
http.cpp:(.text+0xae7): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0xaee): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0xaff): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0xb06): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0xb96): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0xd39): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
build/obj/http.o: In function `Http::getDefaultRequestHeaders()':
http.cpp:(.text+0xe8a): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0xe91): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0xea8): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0xebb): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0xfe3): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0xff3): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0x11a1): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
http.cpp:(.text+0x120c): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
build/obj/http.o: In function `Http::post(QUrl const&, QMap<QString, QString> const&)':
http.cpp:(.text+0x1455): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x147a): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x1558): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x1562): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x156f): undefined reference to `QByteArray::shared_null'
build/obj/http.o:http.cpp:(.text+0x1576): more undefined references to `QByteArray::shared_null' follow
build/obj/http.o: In function `Http::post(QUrl const&, QMap<QString, QString> const&)':
http.cpp:(.text+0x16a0): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0x16a7): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0x1717): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0x1727): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0x1975): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
build/obj/http.o: In function `Http::networkReply(HttpRequest const&)':
http.cpp:(.text+0x1c7d): undefined reference to `QString::arg(unsigned long long, int, int, QChar const&) const'
http.cpp:(.text+0x1c9a): undefined reference to `QByteArray::QByteArray(char const*)'
http.cpp:(.text+0x1dc8): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
http.cpp:(.text+0x1e49): undefined reference to `QString::shared_null'
http.cpp:(.text+0x1e50): undefined reference to `QString::shared_null'
http.cpp:(.text+0x1e7c): undefined reference to `QString::fromAscii(char const*, int)'
http.cpp:(.text+0x1eea): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x1f5c): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0x1f63): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0x1fe1): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x1ff4): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x2084): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x20b5): undefined reference to `QByteArray::realloc(int)'
http.cpp:(.text+0x20cd): undefined reference to `qt_message_output(QtMsgType, char const*)'
http.cpp:(.text+0x219d): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x21bc): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x2225): undefined reference to `QString::free(QString::Data*)'
build/obj/http.o: In function `NetworkHttpReply::replyFinished()':
http.cpp:(.text+0x22be): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x22c6): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x22d7): undefined reference to `QMapData::shared_null'
http.cpp:(.text+0x22de): undefined reference to `QMapData::shared_null'
build/obj/http.o: In function `NetworkHttpReply::NetworkHttpReply(HttpRequest const&, Http&)':
http.cpp:(.text+0x26c4): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x26cb): undefined reference to `QByteArray::shared_null'
http.cpp:(.text+0x2710): undefined reference to `QString::shared_null'
http.cpp:(.text+0x2717): undefined reference to `QString::shared_null'
http.cpp:(.text+0x2743): undefined reference to `QString::fromAscii(char const*, int)'
http.cpp:(.text+0x2797): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x2867): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text+0x28a8): undefined reference to `QByteArray::realloc(int)'
http.cpp:(.text+0x28c0): undefined reference to `qt_message_output(QtMsgType, char const*)'
http.cpp:(.text+0x2a07): undefined reference to `QString::free(QString::Data*)'
build/obj/http.o: In function `QMap<QThread*, QNetworkAccessManager*>::~QMap()':
http.cpp:(.text._ZN4QMapIP7QThreadP21QNetworkAccessManagerED2Ev[_ZN4QMapIP7QThreadP21QNetworkAccessManagerED5Ev]+0x20): undefined reference to `QMapData::continueFreeData(int)'
build/obj/http.o: In function `QByteArray& operator+=<QStringBuilder<QStringBuilder<QByteArray, char>, QByteArray>, char>(QByteArray&, QStringBuilder<QStringBuilder<QStringBuilder<QByteArray, char>, QByteArray>, char> const&)':
http.cpp:(.text._ZpLI14QStringBuilderIS0_I10QByteArraycES1_EcERS1_S4_RKS0_IT_T0_E[_ZpLI14QStringBuilderIS0_I10QByteArraycES1_EcERS1_S4_RKS0_IT_T0_E]+0x45): undefined reference to `QByteArray::realloc(int)'
http.cpp:(.text._ZpLI14QStringBuilderIS0_I10QByteArraycES1_EcERS1_S4_RKS0_IT_T0_E[_ZpLI14QStringBuilderIS0_I10QByteArraycES1_EcERS1_S4_RKS0_IT_T0_E]+0x62): undefined reference to `QByteArray::realloc(int)'
build/obj/http.o: In function `QMap<QByteArray, QByteArray>::detach_helper()':
http.cpp:(.text._ZN4QMapI10QByteArrayS0_E13detach_helperEv[_ZN4QMapI10QByteArrayS0_E13detach_helperEv]+0x1a): undefined reference to `QMapData::createData(int)'
http.cpp:(.text._ZN4QMapI10QByteArrayS0_E13detach_helperEv[_ZN4QMapI10QByteArrayS0_E13detach_helperEv]+0x4a): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
build/obj/http.o: In function `QMap<QThread*, QNetworkAccessManager*>::detach_helper()':
http.cpp:(.text._ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv[_ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv]+0x1a): undefined reference to `QMapData::createData(int)'
http.cpp:(.text._ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv[_ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv]+0x4a): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
http.cpp:(.text._ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv[_ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv]+0x8d): undefined reference to `QMapData::continueFreeData(int)'
http.cpp:(.text._ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv[_ZN4QMapIP7QThreadP21QNetworkAccessManagerE13detach_helperEv]+0xc0): undefined reference to `QMapData::continueFreeData(int)'
build/obj/http.o: In function `QMap<QString, QString>::detach_helper()':
http.cpp:(.text._ZN4QMapI7QStringS0_E13detach_helperEv[_ZN4QMapI7QStringS0_E13detach_helperEv]+0x1a): undefined reference to `QMapData::createData(int)'
http.cpp:(.text._ZN4QMapI7QStringS0_E13detach_helperEv[_ZN4QMapI7QStringS0_E13detach_helperEv]+0x4a): undefined reference to `QMapData::node_create(QMapData::Node**, int, int)'
build/obj/http.o: In function `QDebug::~QDebug()':
http.cpp:(.text._ZN6QDebugD2Ev[_ZN6QDebugD5Ev]+0x39): undefined reference to `QString::free(QString::Data*)'
http.cpp:(.text._ZN6QDebugD2Ev[_ZN6QDebugD5Ev]+0x95): undefined reference to `QByteArray::realloc(int)'
http.cpp:(.text._ZN6QDebugD2Ev[_ZN6QDebugD5Ev]+0xac): undefined reference to `qt_message_output(QtMsgType, char const*)'
collect2: error: ld returned 1 exit status
Makefile:625: recipe for target 'build/target/minitube' failed
make: *** [build/target/minitube] Error 1``

**Comment by fabiodrg666** [comment]
I would say you missed the step to install the Qt modules, the first step from [Build instructions](https://github.com/flaviotordini/minitube#build-instructions) section. Then create your Youtube API key, generate the Makefile with `qmake` and finally compile typing `make`. In my old computer the compilation is taking a while, but without errors

**Comment by fabiodrg666** [comment]
Oh, and don't forget Phonon. I installed `phonon` and one of the backends available, `phonon-backend`, from terminal. Otherwise videos won't play!

**Comment by flaviotordini** [comment]
Closing this
