### ISSUE TITLE
Error transferring [API URL] - server replied: Forbidden

### ISSUE THREAD

**Issue by mhill8** [flaviotordini/minitube#107]
The program compiled and runs okay, but when I type a search term at program start, the left column is taken up by an error message that says "Error transferring https://www.googleapis.com/youtube/v3/search?key=[my_Google_API_key]&part=snippet&type=video&maxResults=50&q=[search_term] - server replied: Forbidden" .  I have an API key registered for Minitube, with no restrictions.

**Comment by flaviotordini** [comment]
Enable the YouTube Data API.

**Comment by webtask-mh** [comment]
Thanks, that did it.  Perhaps that could be added to README.md, in the instructions on how to obtain a Google API key.
