### ISSUE TITLE
403 Forbidden on Search

### ISSUE THREAD

**Issue by Verifirs** [flaviotordini/minitube#109]
Hello, there is an issue with the search function. 
To replicate:
1. Install minitube using AUR or build with working API key.
2. Use search function.
3. Receive "https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&q=test&safeSearch=none 403 Forbidden"

The API key has been tested successfully to work by using this URL "https://www.googleapis.com/youtube/v3/search?key=INSERKEYHERE&q=test&part=snippet" and it returns search results.

**Comment by disconsis** [comment]
Fix in #1 worked for me

**Comment by flaviotordini** [comment]
Can I close this?

**Comment by webtask-mh** [comment]
> Hello, there is an issue with the search function.
> 
>     3. Receive "https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&q=test&safeSearch=none 403 Forbidden"

Verifirs, is this the same as issue #107?  Flavio's comment there resolved it for me.
