### ISSUE TITLE
Missing Icons on Linux in 2.2 due to Qt XDG settings

### ISSUE THREAD

**Issue by darvelo** [flaviotordini/minitube#11]
This has been reported on the [forums](http://flavio.tordini.org/forums/topic/building-minitube-from-git-master-branch-produces-version-2-3-with-some-issues), so just echoing it here. Following this [Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765941), it appears that Minitube is trying to access icon files that don't exist. You can see a list of them in a link at the bottom of the report.

I've possibly narrowed it down to [iconutils.cpp](https://github.com/flaviotordini/minitube/blob/master/src/iconutils.cpp) where it uses [QIcon::fromTheme](http://doc.qt.io/qt-4.8/qicon.html#fromTheme). According to the [freedesktop.org Icon Theme Specification](http://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup) there's an algorithm for finding icons along some directory structure and fallbacks.

**Comment by flaviotordini** [comment]
Yes, icons are loaded by QIcon so it cannot be a Minitube bug. By the way the file paths listed on the bug report look ok to me. Can you give some example of existing icons on your system?

**Comment by darvelo** [comment]
My apologies for the delay - I've been ill.

I think I've figured out the problem. I don't have the icons files that are being searched, as `strace` returns all "not found" errors, but I do have these icon filenames inside some of my icon theme folders in `~/.icons/theme-name`. I suspected that somehow Qt wasn't pointing to the theme I was using, so I searched and found out [how to get GTK+ icon themes in Qt apps](https://wiki.archlinux.org/index.php/Uniform_Look_for_QT_and_GTK_Applications#Using_a_GTK.2B_icon_theme_in_Qt_apps).

I'm not using GNOME, so all I had to do was set `export DESKTOP_SESSION=gnome` in `~/.xinitrc`, reboot (or restart X), and I was good to go!
