### ISSUE TITLE
Support for mpv?

### ISSUE THREAD

**Issue by BurhanDanger** [flaviotordini/minitube#110]
Can mpv support be added ? mpv offers more control over the media than minitube. Even Youtube has arrowkey up/down to volume-control and left/right to seek and f for fullscreen. Can it be made so that video automatically loads in mpv instead of right sidebar or atleast "open in mpv" option like in "open in browser".

**Comment by NamedKitten** [comment]
I'll make a fork with this.

**Comment by flaviotordini** [comment]
No need for a fork, I dropped Phonon and created my own media abstraction library. It supports QtAV and MPV. MPV will be used.
