### ISSUE TITLE
Dependency on gstreamer1.0-libav not specified

### ISSUE THREAD

**Issue by clockworkhawk** [flaviotordini/minitube#112]
I installed minitube 2.9 on Ubuntu 18.04 from https://flavio.tordini.org/on/minitube
it played back the audio, but no video, just black rectangle instead with no errors in console. By tinkering around i found it needs gstreamer1.0-libav package, which is not in .deb package dependencies.

**Comment by elig0n** [comment]
Cool. This solved non-playability for me in WSL.

**Comment by flaviotordini** [comment]
Closing as Phonon is not used anymore
