### ISSUE TITLE
Youtube changed its signature decoding js again

### ISSUE THREAD

**Issue by deesklo** [flaviotordini/minitube#115]
I'm getting the following piece in the js player, which is not matched by the current regex:
```kM=function(a,b,c){b=void 0===b?"":b;c=void 0===c?"":c;var d=new g.nL(a);a.match(/https:\/\/yt.akamaized.net/)||d.set("alr","yes");c&&d.set(b,(0,window.encodeURIComponent)(mL((0,window.decodeURIComponent)(c))));return d};```

The following regex seems to work for me: 
```QRegExp funcNameRe(QString("yt\\.akamaized\\.net/.*d\\.set\\([A-Za-z]+,\\(0,window\\.encodeURIComponent\\)\\(([%1]+)\\(").arg(jsNameChars));```

The thing looks too brittle, but with Youtube changing the code so frequently everything is brittle.

**Comment by flaviotordini** [comment]
Thanks for the heads up! Fixed it. To manually force a refresh delete ~/.local/share/Flavio Tordini/Minitube/functions.js
