### ISSUE TITLE
Video definition switcher is broken

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [flaviotordini/minitube#116]
Since couple of days video definition switcher stopped working. its always getting 360p video. Maybe youtube changed something.

**Comment by avently** [comment]
@flaviotordini please, take a look at this issue. Can't watch a video in normal quality

**Comment by flaviotordini** [comment]
I'm working on it. Will hopefully support all video resolutions in the next release.

**Comment by flaviotordini** [comment]
This is fixed now on git.

**Comment by Michal-Szczepaniak** [comment]
@flaviotordini could you point me to commits which fixed that?

**Comment by flaviotordini** [comment]
Well, there's been some refactoring going on. I don't think you can just cherry pick the commit.
