### ISSUE TITLE
seek slider resets and  jumps when dragged

### ISSUE THREAD

**Issue by trappedinspacetime** [flaviotordini/minitube#118]
Hi,
Thank you for developing this nice app. I installed it from flatpak, it runs well. I know about phonon seek bar issue, I don't know it's related to that bug, when I drag the seek slider to forward, slider position resets to zero then jumps to new dragged position.

**Comment by morfikov** [comment]
I have the same. Sometimes even the current vid is stopped after dragging the seek bar and the next vid on the list is being played. So I have to manually click on the previous one and again drag the seek bar to the desired point.

**Comment by flaviotordini** [comment]
Closing as Phonon is not used anymore.
