### ISSUE TITLE
SSL Handshake failed

### ISSUE THREAD

**Issue by Nolaan** [flaviotordini/minitube#12]
Even with the distributed version or the one I compiled, when I search a term it return this error "La poignée de main SSL a échoué"  (SSL Handshake failed).
Minitube version 2.4

**Comment by flaviotordini** [comment]
Minitube uses Qt for SSL so if there's a bug, it's a Qt bug. I'm not expert enough in SSL to help track your problem.

**Comment by Nolaan** [comment]
SSL Handshakes are not SSL bugs! by uncommenting #ifdef APP_MAC line 177 in src/networkaccess.cpp the app works, I think that is the issue SSL Handshakes problems certainly because of some certificate signature.
