### ISSUE TITLE
Playback fails, misformed URL

### ISSUE THREAD

**Issue by mhill8** [flaviotordini/minitube#120]
When clicking to play from the list of search results, nothing happens.  In the console, I see the message:

400 "Error transferring http:/yts/jsbin/player_ias-vflRtzyEV/en_US/base.js - server replied: Bad Request" QNetworkReply::NetworkError(ProtocolInvalidOperationError)

Is it supposed to be "http://youtube.com/yts/..."?

**Comment by flaviotordini** [comment]
which video?
