### ISSUE TITLE
The flatpak version for Linux does not start videos. 

### ISSUE THREAD

**Issue by ervindine** [flaviotordini/minitube#122]
I have installed the Flatpak version in Fedora, CentOS, Debian and Ubuntu, always with the same result. Videos do not start playing. I tried to report the bug in Flathub but I could not find where or how to. I can play the videos in the browser from minitube and I can also browse and search so I know this is not a network issue or network permission issue.

**Comment by flaviotordini** [comment]
Another broken Linux package. Hardly a news ;) I'm closing this.
