### ISSUE TITLE
Broken subscriptions

### ISSUE THREAD

**Issue by morfikov** [flaviotordini/minitube#126]
It looks like subscriptions stopped working properly. Basically each channel in the subscription list disappears after entering it and quitting after viewing a vid. Moreover, video list isn't ordered and it shows something like this: https://i.imgur.com/cUfk3Ty.png

-- Minitube 3.0

**Comment by flaviotordini** [comment]
Ouch, yes the chronological order is broken. Maybe a YT API bug? I'll investigate. The "disappearing" subscriptions are probably just because you checked "Show Updated" in the status bar.

**Comment by flaviotordini** [comment]
Yes it's YouTube API bug: https://stackoverflow.com/questions/55195054/youtube-data-api-v3-sort-by-date-not-working

**Comment by morfikov** [comment]
> The "disappearing" subscriptions are probably just because you checked "Show Updated" in the status bar.

Yes, I see, I had to accidentally click on it.

**Comment by flaviotordini** [comment]
YT broke the API on purpose in order to "block" sensitive content. So dumb. https://www.reddit.com/r/youtube/comments/b1plj5/sort_by_upload_date_not_working/eiojtjh/

**Comment by morfikov** [comment]
It looks like it's working again.
