### ISSUE TITLE
Providing configurations for building in a config script or file

### ISSUE THREAD

**Issue by pc-magas** [flaviotordini/minitube#127]
Sometimes on compilation we need to compile the `libmpv` from this repo: 
https://github.com/mpv-player/mpv-build

So how I can have a script in order to use it like that:

```
./configure --libmpv_path="somePath" --libqt_path="an_another_path"
```

With that I can specify that the build will be used non-system delivered packages in cases that you want to do a redistribution such as `snap` or `flappack` where all libraries are bundled in a single package-release.

**Comment by flaviotordini** [comment]
This has nothing to do with Minitube or applications in general. It is general system stuff: https://unix.stackexchange.com/questions/22926/where-do-executables-look-for-shared-objects-at-runtime
