### ISSUE TITLE
submodules are not included in release tarball

### ISSUE THREAD

**Issue by dvzrv** [flaviotordini/minitube#128]
I'm currently trying to package 3.0 for Arch Linux, but the release tarball is missing the submodules below `lib`.

Can you upload an asset of that tagged release with the submodules included? Thanks! :)

**Comment by flaviotordini** [comment]
You mean the tarballs generated by GitHub? Can't fix that. Download with:

    git clone --recursive https://github.com/flaviotordini/minitube.git

**Comment by dvzrv** [comment]
Well... and how do I verify those?

**Comment by dvzrv** [comment]
As mentioned in #133, packagers can't verify a tag (unless it's gpg signed), but one can verify the checksum of a release tarball.

Without (gpg) signed tags or without release tarballs including the submodules, the source release degrades in such a way, that I feel uncomfortable further packaging it.

**Comment by flaviotordini** [comment]
I really don't know. How other projects on Github using submodules handle this? What do you actually mean by verify? Isn't something published on this Github repository already verified?

**Comment by dvzrv** [comment]
Other projects work around this by adding a script, that creates a tarball including all the submodules (e.g. I added one for [sc3-plugins](https://github.com/supercollider/sc3-plugins/blob/master/package/create_package.sh), that can optionally also PGP sign the tarball), or by doing it manually (I assume a script is the cleaner and more reproducible way though).

Regarding the verification of something that is put in a git repository: Someone could man-in-the-middle your system, steal your identity, introduce malicious code to the repository and add a new tag or recycle an already existing one.
In such a scenario anyone blindly building from `HEAD` or a certain tagged release will be affected (because a tag is just a pointer to a commit).

The upside to a release tarball is, that its checksum (e.g. `sha256sum`) will change in the above mentioned scenario and downstream (reproducible) builds will break (hopefully raising more than only one eyebrow).
This is obviously a moot point in regards to a newly tagged release, but this is also where PGP signatures come in: If you sign your commits (or a release tarball for that matter and add the signature file to the assets of the release), it's more likely that all of this is actually coming from you.
While it's relatively easy to steal credentials for a website, it's not necessarily super easy to also steal keypairs and the accompanying password to unlock them, unless someone has physical access to your system or introduces malware to it.

As packages on Linux distributions reach many users, we obviously try to not get into a situation, where we blindly build something. :-)
