### ISSUE TITLE
Get debug messages on custom built.

### ISSUE THREAD

**Issue by pc-magas** [flaviotordini/minitube#130]
I have built minitube on ubuntu 18.04LTS but for some reason the video fails to play. Thus I want to check why that happens. 

So how I can get any sort of log in order to find out why that happens? For example if it is an issue with `libmpv` or an http error so I can tell whether is a video playback error or a youtube API error.

**Comment by flaviotordini** [comment]
Just comment DEFINE+=QT_NO_DEBUG_OUTPUT in minitube.pro
