### ISSUE TITLE
Install libmpv1 0.29 on Linux Mint (probably Ubuntu 18.04 too)

### ISSUE THREAD

**Issue by Estavann** [flaviotordini/minitube#131]
I had problems installing minitube 3.0. I installed a newer version of qt (it was 5.9, and minitube requires 5.11). I managed to come to this error.
"minitube: symbol lookup error: minitube: undefined symbol: mpv_render_context_create". Then the problem with libmpv started. Linux mint 19.1 is based on bionic. I've fooled the repositories and changed them to these from Ubuntu Cosmic.

etc/apt/sources.list to this:
https://pastebin.com/8MpjqUcP

Then sudo apt-get update and 
sudo apt-get install libmpv1

After installing libmpv1, the minitube has started up. I hope that it will be helpful for someone. 
Maybe it's too stupid solution, but I'm a fresh linux user
Greetings ;)

**Comment by DeftNerd** [comment]
This was tempting to me, but when Apt reported that there are 1,373 packages to update, I had to say no. That's just too much that could go wrong IMHO. Minitube is important enough to me that I gave serious consideration to running apt on an incorrect set of repos or dropping Linux Mint for Ubuntu 18.10, but It's just too much change for my work computer just for a single program.

**Comment by flaviotordini** [comment]
@DeftNerd Don't do that!

**Comment by pc-magas** [comment]
In my case I installed `libmpv` by manually compiling it using the following commands:
```
sudo apt-get install git dh-autoreconf build-essential libfreetype6-dev libfribidi-dev libfontconfig1-dev yasm libmp3lame-dev libx264-dev libfdk-aac-dev python
git clone https://github.com/mpv-player/mpv-build.git
cd `mpv-duild`
cd mpv-build
echo --enable-libx264 >> ffmpeg_options
echo --enable-libmp3lame >> ffmpeg_options
echo --enable-libfdk-aac >> ffmpeg_options
echo --enable-nonfree >> ffmpeg_options
echo --enable-libmpv-shared > mpv_options
./use-mpv-custom v0.29.0
./update
./rebuild -j4
sudo ./install
cd ..
```

Try to manually install it and reinstall the deb. Btw how you installed later libqt version?

**Comment by vitovt** [comment]
It works. But no sound with minitube ((
