### ISSUE TITLE
Build Error: media.h not found

### ISSUE THREAD

**Issue by kartik-ynwa** [flaviotordini/minitube#132]
Hello.

I am trying to package the 3.0 update for Void Linux. However, while compiling I get the following error.

```
In file included from src/main.cpp:26:
src/mainwindow.h:26:10: fatal error: media.h: No such file or directory
 #include "media.h"
          ^~~~~~~~~
compilation terminated.
```

I am inexperienced with C++ so I am unsure how to fix this. Any pointers would be appreciated.

If it is of any value, the template for the build (similar to Arch PKGBUILD) I tried is here: https://github.com/kartik-ynwa/void-packages/blob/27f3ab60c11de7b97afc500c6784da1caa6d8350/srcpkgs/minitube/template

Thanks in advance.

**Comment by flaviotordini** [comment]
Make sure to clone with the --recursive option:

    git clone --recursive https://github.com/flaviotordini/minitube.git

**Comment by kartik-ynwa** [comment]
Cheers. Thanks a lot.
