### ISSUE TITLE
submodule tarballs

### ISSUE THREAD

**Issue by ArmedAviator** [flaviotordini/minitube#133]
Can you please make release tarballs of the submodules required to build?  It would make it easier to download and build in a package manager.  That way SHA/MD5 sums can be checked and no unexpected changes in source code appear when generating the package.

**Comment by dvzrv** [comment]
Seems this is intended behavior. #128

**Comment by ArmedAviator** [comment]
If the releases are made on each submodule repo, distro package maintainers would not have to worry about changes they are not aware of each time they build the package.  If releases are made for each subvolume, they don't change.

Better yet, if there's a way to build the release with the submodules included.....but last I've read from circa 2016, Github does not give that option in an automated way - it'd require manual recursive clone and then tarball that clone.

**Comment by flaviotordini** [comment]
AFAIK submodules point to a specific commit. For example, If you checkout the 3.0 tag with recursive option you'll always get the submodules version used at the time of the release.

**Comment by ArmedAviator** [comment]
The problem remains, however.  Distros will not package minitube 3.0 without either:
1) minitube package containing the submodules
2) each of the submodules have a release download available (.tar.gz)

Take a look at various distros.  Gentoo, Ubuntu, Arch, and Void Linux are the few I've checked.  None have and likely will not have minitube-3.0 packaged due to this issue.

**Comment by ArmedAviator** [comment]
I just experimented a bit...

It looks like you can upload your own binary for inclusion with a release.  Assuming you have a UNIX-like OS, do the following:

```
mkdir -p /usr/src/make-release
cd /usr/src/make-release
git clone --recursive https://github.com/flaviotordini/minitube.git minitube-3.0
rm -rfv minitube-3.0/.git*
tar -czvf minitube-3.0.tar.gz minitube-3.0
```


Upload the resulting minitube-3.0.tar.gz file to the release in Github.

**Comment by flaviotordini** [comment]
I don't get it. Submodules are for my own use. I share code among my projects. They are not libraries to be packaged separately and loaded as shared objects. Please enlighten me on the logic behind all this.

**Comment by ArmedAviator** [comment]
The submodules are used to compile minitube.  Without the submodules, the required libraries are missing and will not compile.

To be properly built by any reputable distro (Linux, BSD, etc.) you need to have all of the files necessary to build the application in a downloadable binary format (.tar.bz, .tar.gz, .zip, etc.) which will always be consistent per version.  Checking the MD5, SHA1, SHA256 sums should always be verified of the binary package at the build-site to ensure it is unchanged from the time the downstream maintainers (Arch, Gentoo, Void, Debian, etc.) defined how to build the package from source.

If you do the above commands that I listed, it will create a tarball of minitube version 3.0 plus the required submodules all in a single download package.  This is what downstream package maintainers want.

**Comment by flaviotordini** [comment]
What about downloading the current tar.gz and checking its hash. Then

    git submodule update --init --recursive

Yes, that add sources but from a secure source like GitHub. Another question: since these distributions will also create a source package, why can't they build using the sources they themselves packaged?

**Comment by ArmedAviator** [comment]
This does not limit the submodules to a specific commit with that command, so any updates made on the repository can make their way into the package, unknowingly to the downstream package maintainers.  The distro I'm packaging this for won't accept it into their package repository using the method you proposed (https://github.com/void-linux/void-packages/pull/10994).  Additionally, this requires another build-time dependency to be installed that wouldn't otherwise - git.

Yes, most distros provide binary packages, but those binary packages need to be built multiple times for various architectures and c libraries (i.e. glibc vs musl).  If a distro maintainer finds an error in their build script, they may have to rebuild it again against upstream and it should not contain changes if they did not intend it to include them.  Some distros do not provide binary packages.  An example is Gentoo's ebuild system.  Gentoo just downloads metadata of packages and when a user chooses to install a package, the metadata (ebuild) tells the package manager what to download, how to compile it, and where to install it.  Most distros will not allow packages that require git to build correctly.

See my above commands to make a single binary package that contains everything needed that makes all downstream package maintainers happy.

**Comment by flaviotordini** [comment]
Yes, it limits the submodules to a specific commit. Just type:

    git submodule status

To see the actual commits submodules point to. I get your point on the git dependency. In the end, this boils down to more work for upstream or more work for the distro.

**Comment by ArmedAviator** [comment]
In any case, the release tarball provided by Github does not contain git information:

> rich@area51 /usr/src $ tar xf 3.0.tar.gz 
> rich@area51 /usr/src $ cd minitube-3.0/
> rich@area51 /usr/src/minitube-3.0 $ git submodule update --init --recursive
> fatal: not a git repository (or any of the parent directories): .git

Since it is unable to even download the submodules, your proposed method also fails.

Please make an all-inclusive tarball.

**Comment by dvzrv** [comment]
As mentioned in #128, there are options to create a tarball including the submodules, using a script.
@flaviotordini If you like, I can add a pull request for something like that.

**Comment by dvzrv** [comment]
@flaviotordini I'd be happy, if you considered my pull request #139 for solving this issue and #128.
Thanks! :)

**Comment by flaviotordini** [comment]
Thanks for the script. 3.1 tarball is available.
