### ISSUE TITLE
DEB package missing dependency

### ISSUE THREAD

**Issue by proedie** [flaviotordini/minitube#134]
When trying to install Minitube 3.0 on Ubuntu <18.10 installation works fine despite the fact that Qt 5.11 is required. Minitube then fails to run saying:

`minitube: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version 'Qt_5.11' not found (required by minitube)`

Qt 5.11 should be added as a dependency to the DEB package in order to prevent installing in the first place.

**Comment by thewolfwillcome** [comment]
AFAIK this project doesn't provide deb packages. So you must contact the maintainer of the minitube deb package for Ubuntu.
Where did you get the deb package?

**Comment by proedie** [comment]
> Where did you get the deb package?

Ummm. I found it on this little website: https://flavio.tordini.org/files/minitube/minitube.deb

**Comment by flaviotordini** [comment]
The package is currently for Ubuntu >= 20.04. I build the package on the latest Ubuntu LTS.

**Comment by proedie** [comment]
I would like to ask this to be re-opened.

The problem is not that my Ubuntu version was not supported, the problem is that I was able to install Minitube when it should not have been possible.

OT: Are you now supporting the latest LTS in general?

**Comment by useretail** [comment]
Possible solution: #179
