### ISSUE TITLE
build on arm failed

### ISSUE THREAD

**Issue by johnMinelli** [flaviotordini/minitube#141]
i'm trying to build the repo on a Raspberry 3B+ Debian 9 Stretch. I got this error:

In file included from lib/media/src/mpv/mediampv.cpp:7:0:
lib/media/src/mpv/mpvwidget.h:7:27: fatal error: mpv/render_gl.h: File o directory non esistente
 #include <mpv/render_gl.h>
compilation terminated.

Mpv is already installed. How can i solve it?

**Comment by flaviotordini** [comment]
You need MPV >= 0.29.0
