### ISSUE TITLE
(OSX) Version 2.4 no longer playing videos

### ISSUE THREAD

**Issue by mrkapqa** [flaviotordini/minitube#142]
Hello ,

i have been using for quite some time Version 2.4 on Mac but i noticed that it is no longer playing video.
The error is "no active input".

It used to function before so i am wondering what happened.

**Comment by flaviotordini** [comment]
Just updated to the latest version. Currently 3.1

**Comment by mrkapqa** [comment]
Hello, thank you, grazie.

Updated to MacOS 10.11.6 - the current version wouldn't open.
Is there a version compatible and still functional with this OS?
