### ISSUE TITLE
Is there a way to control the playback via keyboard?

### ISSUE THREAD

**Issue by foxnoodles** [flaviotordini/minitube#150]
First of all kudos to the dev, love this app, keep up the great work!

As for the question, I'd love to be able to control the playback just like on Youtube. Kinda like this: https://support.google.com/youtube/answer/7631406?hl=en 

Can't seem to find any way to do it. Am I missing something or it's just no implemented yet?

**Comment by flaviotordini** [comment]
Check the menus for keyboard shortcuts. I think the only missing feature is "Seek 10 seconds".

**Comment by foxnoodles** [comment]
Well no, there are a lots of stuff missing besides "Seek 10 secs" and the shortcuts should be in compliance with youtube I assume. Otherwise, it kinda breaks the UX. 
Also, the play/pause shortcut doesn't work when the sidebar is active. Meaning the elements in the sidebar get "focused".  I think everything besides up/down arrow keys and "enter" should be ignored in sidebar. That way you'll be able to navigate through videos with keys and play them by hitting enter while the space bar will still work as a global key for play/pause in the main player.

As for the missing shortcuts here's the list of missing ones which alotta pips use on regular basis:

1. Seek backward/forward 5 seconds.
2. Seek backward 10 seconds in player.
3. Seek forward 10 seconds in player.
4. Increase/Decrease volume 5%.
5. Seek to 0% to 90% of the video. (using number keys)

**Comment by foxnoodles** [comment]
Also, I don't get why is the fullscreen shortcut control+cmd+f?  Why not just F. Are we expecting to use F letter anywhere besides typing in the search field?

**Comment by flaviotordini** [comment]
These features are in 3.4
