### ISSUE TITLE
Playback does not work with a resolution higher than the video.

### ISSUE THREAD

**Issue by pomputer** [flaviotordini/minitube#164]
I used to be able to play 1080p videos on my 4k monitor without setting the resolution to 1080p in minitube. Now if the resolution is set to greater than the video, it plays audio but only a black screen. I use Archlinux.

**Comment by thewolfwillcome** [comment]
Do you have an example video where the problem occurs.

**Comment by pomputer** [comment]
I just tried it and looks like the latest update (or one of the latest updates) makes me unable to play any content with a smaller resolution than 4k (my monitor resolution). I can record a video if you wish.

**Comment by thewolfwillcome** [comment]
An example youtube video is needed which causes the problem for you.
Otherwise there is no way to reproduce it especially I don't have an 4K monitor at hand

**Comment by pomputer** [comment]
Here is a video I recorded about the issue:[https://www.youtube.com/watch?v=Z1j0cE6jsC4&feature=youtu.be]( https://www.youtube.com/watch?v=Z1j0cE6jsC4&feature=youtu.be)

**Comment by ejuarezg** [comment]
I am having the same issue.

**Comment by pomputer** [comment]
Looks like it is now fixed after updating my installation.
