### ISSUE TITLE
Keep skipping playlist videos

### ISSUE THREAD

**Issue by benchile55** [flaviotordini/minitube#167]
Hello,

I am using archlinux rolling release and it worked well until the first-second week of July. And last week it started keep skipping the playlist the videos again, it was doing like 2 months ago. I add the terminal running minitube app: 
https://i.imgur.com/9Z9jacU.png

**Comment by flaviotordini** [comment]
Thanks for the heads up. I modified the js functions. Let me know if the problem persists.

**Comment by benchile55** [comment]
> Thanks for the heads up. I modified the js functions. Let me know if the problem persists.

Good day 

Thanks for that modification.. I re installed and recompiled minitube 3.4 and now it is working  good 100% again!  Amazingly you did the trick and  worked out great.
+1:
