### ISSUE TITLE
'class CachedHttp' has no member named 'getValidators'

### ISSUE THREAD

**Issue by CdeMills** [flaviotordini/minitube#169]
Hello,
compiling from source checked out from github on CentOS-8 x86_64. minitube version is  3.5.1; qt-devel is 5.12.5. 

Did  qmake-qt5 followed by make, resulting in:

g++ -c -pipe -O2 -std=gnu++1z -fno-exceptions -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=3.5.1 -DAPP_NAME=Minitube -DAPP_UNIX_NAME=minitube -DAPP_SNAPSHOT -DQT_NO_DEBUG_OUTPUT -DQT_USE_QSTRINGBUILDER -DQT_STRICT_ITERATORS -DQT_DEPRECATED_WARNINGS -DHTTP -DMEDIA_MPV -DAPP_LINUX -DDATADIR=\"/usr/share\" -DPKGDATADIR=\"/usr/share/minitube\" -DUPDATER -DUPDATER_DEFAULT -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Ilib/http/src -Ilib/idle/src -Ilib/media/src -Ilib/media/src/mpv -Isrc/qtsingleapplication -Isrc/invidious -Isrc -Ilocale -Ilib/updater/src -Ilib/updater/src/impl -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -Ibuild/moc -I/usr/lib64/qt5/mkspecs/linux-g++ -o build/obj/src/invidious/invidious.o src/invidious/invidious.cpp
src/invidious/invidious.cpp: In lambda function:
src/invidious/invidious.cpp:47:21: error: 'class CachedHttp' has no member named 'getValidators'
         cachedHttp->getValidators().insert("application/json", [](const auto &reply) -> bool {

Sources up to src/qtsingleapplication/qtlocalpeer.cpp compile OK. Version 3.5 did compile to the end, and the executable is working.

Any idea ?

Regards
Pascal

**Comment by sur5r** [comment]
Seems like your `lib/http` submodule is out of date. Try `git submodule --update`.

**Comment by CdeMills** [comment]
Hmmm ... it compiles better this way. Thank you.

Pascal
