### ISSUE TITLE
Where to put API key?

### ISSUE THREAD

**Issue by riveravaldez** [flaviotordini/minitube#171]
Hi, this seems to be an old and very usual issue but after trying different locations and formats I'm still unable to make it work.

Here?  → /etc/profile.d/minitube.sh
export GOOGLE_API_KEY="xxx"

or:

.config/Flavio Tordini/Minitube.conf ?

Tried in both and result is the same (403 Forbidden).

Sorry to ask, but couldn't find no clear instruction. (Minitube already installed in an updated Debian Stable.)

Thanks a lot.

**Comment by flaviotordini** [comment]
You don't need it anymore. Just use the latest version. The README got updated and info removed.
https://github.com/flaviotordini/minitube/commit/7b4ef7f8aa76f316e1396a0b7b7dcde4874e0ede#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by riveravaldez** [comment]
Hi, thanks for your response, Flavio.
I understand that the idea is to use that latest version (downloaded as a binary/.deb file from your site?), but I've already installed the version from the official repositories. Is it possible to use my API key with this already installed version?
If it's possible, where and how should I put it?
Thanks a lot and sorry to insist.

**Comment by riveravaldez** [comment]
> You don't need it anymore. Just use the latest version. The README got updated and info removed.
> [7b4ef7f#diff-04c6e90faac2675aa89e2176d2eec7d8](https://github.com/flaviotordini/minitube/commit/7b4ef7f8aa76f316e1396a0b7b7dcde4874e0ede#diff-04c6e90faac2675aa89e2176d2eec7d8)

Hi, thanks for your response, Flavio.
I understand that the idea is to use that latest version (downloaded as a binary/.deb file from your site?), but I've already installed the version from the official repositories. Is it possible to use my API key with this already installed version?
If it's possible, where and how should I put it?
Thanks a lot and sorry to repeat.

**Comment by flaviotordini** [comment]
It should prompt you. Btw, you can build by yourself no need to use a binary.

**Comment by riveravaldez** [comment]
Thanks again, @flaviotordini. I'm sorry but I'm not seeing any prompt about this, where should it be?
And thanks for mention the building option. Because there's a version in official repositories and I already have an API key I'm trying first to use that and make it work (hope there's a way).

**Comment by flaviotordini** [comment]
It should show a dialog.

**Comment by flaviotordini** [comment]
...for versions < 3.5
