### ISSUE TITLE
error while loading shared libraries: libQt5X11Extras.so.5

### ISSUE THREAD

**Issue by michalzkosmosu** [flaviotordini/minitube#172]
After I installed Minitube via .deb file from official site, on Linux Mint 20 app don't show up.
When I run 'minitube' in Terminal I see: 'minitube: error while loading shared libraries: libQt5X11Extras.so.5: cannot open shared object file: No such file or directory' – what could help me?

**Comment by flaviotordini** [comment]
Thanks for the report. Install libqt5x11extras5 . I'll fix this for the next release.

**Comment by flaviotordini** [comment]
Fixed in 3.6.2
