### ISSUE TITLE
(libmpv1) mpv installed manually - how to skip dependency error

### ISSUE THREAD

**Issue by mrkapqa** [flaviotordini/minitube#174]
Hello Flavio,

i installed version 3.2 on Ubuntu 18.04 and it would complain of error

` minitube depends on libmpv1 (>= 0.29.0); however:
  Package libmpv1 is not installed.
`

however, i have mpv + vapoursynth installed manaully

`mpv 0.32.0-714-g5a4fc8684e Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Sep  7 19:40:16 CEST 2020
`

how can i overcome the error?

thank you very much.

**Comment by flaviotordini** [comment]
Search Google on how to force a package install on Debian. This is not a Minitube bug.
