### ISSUE TITLE
Minitube.exe is detected as virus on Windows 10

### ISSUE THREAD

**Issue by Mennaruuk** [flaviotordini/minitube#178]
[VirusTotal scan](https://www.virustotal.com/gui/file/82f6e9c5c6c274869c6835ebe139da5b53b905c631dd07602448a30d67d3a9d5/detection) for the Minitube.exe file found inside the uncompressed exe file.

What Microsoft Defender Antivirus on Windows 10 says:
![IMG_2557](https://user-images.githubusercontent.com/52135169/98612950-4f56fc80-22c3-11eb-9785-f75f6c5a0822.jpeg)

Is it safe to install Minitube?

**Comment by flaviotordini** [comment]
I'll have a look. I build on a very clean Windows 10 virtual machine.

**Comment by Mennaruuk** [comment]
Thank you! I got in touch with Microsoft, their opinion is that this was incorrectly marked as a Trojan, and they were able to get rid of the false positives! I also submitted the file to SecureAge APEX to analyze and they removed the false positive as well. Unfortunately, Cybereason seems to be the only antivirus company that marks Minitube as false positive.

**Comment by flaviotordini** [comment]
Thank you. Much appreciated.

**Comment by Mennaruuk** [comment]
Got in touch with Cybereason and they got rid of the last false positive!

**Comment by Mennaruuk** [comment]
Hi Mr. Tordini, the virus alert is back up again. Do you know what's exactly causing this? For a while, Windows didn't think it malicious until a couple of weeks ago when a similar alert started popping up.
