### ISSUE TITLE
Add to -rpath to increase portability of executables

### ISSUE THREAD

**Issue by useretail** [flaviotordini/minitube#179]
Problem: minitube complains about missing libs, despite the fact that Qt 5.12 is correctly installed:
_minitube: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.12' not found (required by ./minitube)_

Solution:
Issue happens because most users have Qt installed in /usr/lib/x86_64-linux-gnu (or another path) by distro which ld will use by default. To avoid such issues you can compile with -rpath or run with LD_LIBRARY_PATH=/path/to/your/Qt/libs/location to help linker find needed Qt version.

**Comment by flaviotordini** [comment]
Sorry I do not really understand this.I do not ship Qt libs on Linux, but depend on system Qt libs. Why should I set a rpath and to which path?
