### ISSUE TITLE
minitube + windows 7 > no search results

### ISSUE THREAD

**Issue by mrkapqa** [flaviotordini/minitube#180]
Hello Flavio,

i am reporting here issue with latest version and windows 7.
am getting no search results in demo version.

maybe i am needing some additonal windows package?

thank you very much for a beautiful software.

**Comment by flaviotordini** [comment]
Seems to work for me. Can you try from another device/OS?

**Comment by mrkapqa** [comment]
thanks flavio, just tried with windows 10 (1809), same issue.

**Comment by flaviotordini** [comment]
Try with the new 3.6.6 update

**Comment by mrkapqa** [comment]
could you please share this version 3.6.6 here Flavio? 
version 3.8.1 does not function on my Windows 7, no search results.
Thanks.
