### ISSUE TITLE
no search results

### ISSUE THREAD

**Issue by aldercanoe** [flaviotordini/minitube#181]
Hello Flavio,

I am reporting here issue with debian testing and minitube 3.6.5
am getting no search results (black screen). But browsing works and I can play the videos.
If I start minitube from the console the following message is displayed.
'QObject::connect(QWindow, SearchView): invalid nullptr parameter'
How can I fix it?

**Comment by flaviotordini** [comment]
Search is working for me. Is this still happening?

**Comment by aldercanoe** [comment]
Yes it is still happening. Everything in the system is up to date (apt update..) and I don't know where to search or debug the mistake.

**Comment by flaviotordini** [comment]
Try 3.6.6. Let me know.

**Comment by aldercanoe** [comment]
I have to install two dependencies 'libmng1, qt5-image-formats-plugins' then it works.
Thanks a lot! Can you please explain to me why it doesn't work?

**Comment by flaviotordini** [comment]
qt5-image-formats-plugins is now required and documented in the README,
don't know about libmng1, is it a dependency of qt5-image-formats-plugins?
I will check.
