### ISSUE TITLE
Search results do not display unless 'Show More' is double clicked (Qt5 5.12.10)

### ISSUE THREAD

**Issue by darkshram** [flaviotordini/minitube#182]
The search results are not displayed unless 'Show More' is double clicked.

minitube 3.6.7 (also happens with previous 3.6.x releases)
Qt5 5.12.10 (LTS)
MPV 0.33
OS: ALDOS Linux 1.4.15

```
QObject::connect(QWindow, SearchView): invalid null parameter
qml: Failed to parse data: TypeError: Cannot read property '1' of null
```

**Comment by flaviotordini** [comment]
Works for me. Is it still happening?
