### ISSUE TITLE
Search results come blank screen with some google api link?

### ISSUE THREAD

**Issue by spectrumgamer75** [flaviotordini/minitube#185]
Hello,
I am trying to get minitube running on my raspberry pi. I downloaded the latest version available in the repository. It launches fine but whenever I try to search anything it returns blank page with some link on the top like googleapis.com or something. I can't find the latest .deb file anywhere and trying to compile it gives this error:
```
/usr/bin/ld: build/obj/lib/http/src/cachedhttp.o: file not recognized: file truncated
collect2: error: ld returned 1 exit status
make: *** [Makefile:756: build/target/minitube] Error 1

```
I have my api key too, any way to like update the api key with mine?
PLease help me fix this issue, really wanted to try out mini tube :+1:

**Comment by flaviotordini** [comment]
Are you sure that's the latest version? Sounds like an older version to me.

**Comment by spectrumgamer75** [comment]
I want the .deb file for the raspberry pi (ARM), but the given one is only for amd64 (ubuntu)

**Comment by spectrumgamer75** [comment]
Seems like the new version is there in debian 11 (testing):
https://debian.pkgs.org/11/debian-main-armhf/minitube_3.6.1-1_armhf.deb.html

But since Raspberry Pi OS currently uses Buster I am unable to install that .deb file.

**Comment by flaviotordini** [comment]
I see. Latest version is 3.6.7. You can try building by yourself.

**Comment by denizdogan** [comment]
I don't know if this is the same problem, but I built the latest master branch just today on Raspberry Pi OS and the search looks empty. If I mouseover the search results list, I can see a magnifying glass icon at the bottom right. The terminal outputs `Error "SyntaxError: Expected token` repeatedly, once every second. When I mouseover some parts of the search results area, the cursor changes to a pointer. It's almost as if the text is transparent or something. When I click, nothing happens.

```
$ ./build/target/minitube 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QObject::connect: invalid null parameter
qt5ct: custom style sheet is disabled
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
```

![image](https://user-images.githubusercontent.com/50928/102241148-ee8d9600-3ef8-11eb-9340-6c847e09f4d2.png)
