### ISSUE TITLE
Build error : src/main.cpp:86:22: error: ‘AA_UseHighDpiPixmaps’ is not a member of ‘Qt’

### ISSUE THREAD

**Issue by chdrsto** [flaviotordini/minitube#19]
I'm getting an error message while trying to build:

src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:86:22: error: ‘AA_UseHighDpiPixmaps’ is not a member of ‘Qt’
     app.setAttribute(Qt::AA_UseHighDpiPixmaps);
                      ^
make: *** [build/obj/main.o] Fehler 1

Following setup I'm using:
Project MESSAGE: Building Minitube 2.5
Project MESSAGE: Qt 4.8.6 in /usr

**Comment by flaviotordini** [comment]
You have to build with Qt 5. My bad for not updating the README. Will do.
