### ISSUE TITLE
Error During Build

### ISSUE THREAD

**Issue by Fabioamd87** [flaviotordini/minitube#191]
Hello,
I am trying to build minitube on raspberry pi 4 with raspbian buster, but I get this error

src/yt/invidious/invidious.cpp:3:10: fatal error: cachedhttp.h: File o directory non esistente
 #include "cachedhttp.h"
          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:2237: build/obj/src/yt/invidious/invidious.o] Error 1

Thanks.

**Comment by sur5r** [comment]
See https://github.com/flaviotordini/minitube/issues/175#issuecomment-711033614
