### ISSUE TITLE
Error During Search

### ISSUE THREAD

**Issue by Fabioamd87** [flaviotordini/minitube#192]
Hello!
I build minikube from git, but when i search for a video I get this error:

qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QObject::connect: invalid null parameter
qt5ct: custom style sheet is disabled
Error "SyntaxError: Expected token `)'"

during the search phase the last error keep showing, like a ping:

Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
[...]

Thanks!

**Comment by nightcat2005** [comment]
The same issue for all actions (search, play, etc.)

Error "SyntaxError: Expected token `)'"
Error "SyntaxError: Expected token `)'"
...

**Comment by flaviotordini** [comment]
Qt version?

**Comment by Fabioamd87** [comment]
pi@raspberrypi:~ $ qmake --version
QMake version 3.1
Using Qt version 5.11.3 in /usr/lib/arm-linux-gnueabihf
pi@raspberrypi:~ 

Thanks

**Comment by flaviotordini** [comment]
You need Qt 5.12
