### ISSUE TITLE
Google API key - Shouldn't it be provided by minitube?

### ISSUE THREAD

**Issue by tetris4** [flaviotordini/minitube#2]
Hello,

We are trying to package minitube for our distribution (Chakra) and are wondering why minitube doesn't provide the developer key. Does it make sense for a packager or distribution to maintain a developer key? Wouldn't it be more reasonable for you to provide this in the minitube source? 

Thank you.

**Comment by flaviotordini** [comment]
Of course not. API keys should not be shared. Moreover API keys have a limited quota. Above a certain threshold you will have to pay Google. Have a look here: https://developers.google.com/console/help/new/?hl=en_US#apikeybestpractices

**Comment by tetris4** [comment]
If API key should not be shared, how are distributions supposed to implement them...
In any case, thank you for the insight and excuse my ignorance. Took the opportunity to do some further studying on the subject, this was an interesting read:
http://lwn.net/Articles/570485/

**Comment by flaviotordini** [comment]
Yes, API keys and the FOSS world are a bad match.

**Comment by sloth1** [comment]
I guess minitube is dead. :( My whole reason for using it was google avoidance / direct video access. Maybe someone could create a large pool of keys we could share?
