### ISSUE TITLE
Minitube 2.5 will not start on Linux 32bit

### ISSUE THREAD

**Issue by TheBlackViper1996** [flaviotordini/minitube#20]
Minitube no longer starts and when run from the terminal it shows this error:
"minitube: symbol lookup error: minitube: undefined symbol: _ZN21QAbstractConcatenable14appendLatin1ToEPKciP5QChar"

**Comment by flaviotordini** [comment]
Distro? Qt version?

**Comment by Metalsasi** [comment]
I have the same error message.

I am running it on Lubuntu 14.04 32bit
and Minitube has installed Qt version 5.2.1+dfsg libraries as depencies.

**Comment by Crihub** [comment]
Same here:
    QIODevice::read: device not open
    minitube: symbol lookup error: minitube: undefined symbol: _ZN6QDebugD1Ev

System: debian wheezy/sid

minitube dependencies installed:
libphonon4qt5-4 4:4.8.0-4
libqt5dbus5 5.3.2+dfsg-4+deb8u1
libqt5network5 5.3.2+dfsg-4+deb8u1
libqt5script5 5.3.2+dfsg-2
libqt5sql5 5.3.2+dfsg-4+deb8u1
libqt5sql5-sqlite 5.3.2+dfsg-4+deb8u1
libqt5widgets5 5.3.2+dfsg-4+deb8u1
phonon4qt5 4:4.8.0-4
phonon4qt5-backend-gstreamer 4:4.8.0-3

**Comment by flaviotordini** [comment]
Looks like a binary incompatibility with erlier Qt versions.

**Comment by flaviotordini** [comment]
"The Qt version 5.5 series is binary compatible with the 5.4.x series.": http://code.qt.io/cgit/qt/qtbase.git/tree/dist/changes-5.5.0

So any Qt version before 5.4 won't be compatible. You need to build for yourself. And let's hope no >=5.4 API is used.

**Comment by TheBlackViper1996** [comment]
Your solution of "built for yourself" is unacceptable, you are alienating the average user who will not know how to do that.

**Comment by flaviotordini** [comment]
Unacceptable? I can support only a limited subset of distros/versions. I simply build a .deb package using the latest Ubuntu version. That's it. Anything else is for Linux packagers. Please complain to your distro for not providing an updated package.

**Comment by Crihub** [comment]
Thanks Flavio for clarifying this. Since I can't install minitube 2.5 on my system (Debian has libqt 5.3.x) at least I'd like to re-install minitube 2.4; can you please tell me where I can find a 2.4 .deb package on your website?

**Comment by flaviotordini** [comment]
http://flavio.tordini.org/files/minitube/minitube_2.4_i386.deb
or
http://flavio.tordini.org/files/minitube/minitube_2.4_amd64.deb

**Comment by TheBlackViper1996** [comment]
For the record I am using the Linux distribution that the majority of people will be using, Ubuntu 14.04.3 LTS.
You cannot base Minitube on a version most people won't be using such as Ubuntu 15.04 or 15.10.

**Comment by flaviotordini** [comment]
@TheBlackViper1996 my binaries have always been a "best effort", not meant to work on all possible distro versions. The proper way is to create a package for 14.04 and that's a job for Debian or Ubuntu packagers.
