### ISSUE TITLE
Play YT URL

### ISSUE THREAD

**Issue by cederom** [flaviotordini/minitube#203]
Hello world :-)

Thank you for this marvelous application! I really dislike Google and YouTube for the direction they took recently - slow as hell, lots of ads, even I was Premium member I could not subscribe to more than 2k channels, etc etc etc. This application is great alternative to all this bullshit and still I can watch some interesting videos folks post on YT.

There is one feature missing - opening a video URL - search does not always work for non public videos that I know URL of and I would love to watch them in MiniTube. Please add this functionality to open videos at given URL :-)

Thank you :-)
Tomek

**Comment by LargePrime** [comment]
when finding a YT URL I would like to watch on Minitube, I find pasting it in the search crashes the application.

So I would like to be able to use Minitube as the poster above suggests.

**Comment by flaviotordini** [comment]
Fixed in 3.9

**Comment by cederom** [comment]
THANK YOU @flaviotordini =)
