### ISSUE TITLE
x11-extras: Qt6

### ISSUE THREAD

**Issue by EricoDeMecha** [flaviotordini/minitube#206]
Error building with qmake

<pre>Project MESSAGE: Building Minitube 3.9
Project MESSAGE: Qt 6.1.1 in /opt/qt6
Project MESSAGE: Building for release
Project MESSAGE: QT: core gui widgets network sql qml dbus x11extras dbus
Project MESSAGE: CONFIG: lex yacc debug exceptions depend_includepath testcase_targets import_plugins import_qpa_plugin file_copies qmake_use qt warn_on release link_prl incremental release shared plugin_manifest linux unix posix gcc c++17 exceptions_off rtti_off object_parallel_to_source optimize_full
Project MESSAGE: DEFINES: APP_VERSION=3.9 APP_NAME=Minitube APP_UNIX_NAME=minitube APP_SNAPSHOT QT_NO_DEBUG_OUTPUT QT_USE_QSTRINGBUILDER QT_STRICT_ITERATORS QT_DEPRECATED_WARNINGS HTTP MEDIA_MPV APP_LINUX DATADIR=\&quot;/usr/share\&quot; PKGDATADIR=\&quot;/usr/share/minitube\&quot;
Project MESSAGE: QMAKE_CXXFLAGS: -pipe
Project MESSAGE: QMAKE_LFLAGS:
Project ERROR: Unknown module(s) in QT: x11extras
</pre>

**Comment by flaviotordini** [comment]
You cannot build with Qt 6
