### ISSUE TITLE
Fail on some subscribed YouTube channels: Error "Error: Request failed with status code 404"

### ISSUE THREAD

**Issue by alicavus** [flaviotordini/minitube#207]
I installed minitube (latest release 3.9) from official repositories on Arch Linux. When I subscribed to some channels and later try to access it I get  "Error: Request failed with status code 404". When I try to search the same channel I can find it and subscribe again, in "Subscribtions" section there are shown two different subscribtions:
![image](https://i.ibb.co/W58L5nM/Screenshot-from-2021-07-19-09-06-34.png)
Channel subscribed during current search session is working, a former is failing loadindg the channel:
![image](https://i.ibb.co/DWxR9dy/Screenshot-from-2021-07-19-09-24-52.png)

Here is output of `journalctl /usr/bin/minitube`
```
Jul 19 09:02:05 PATRGRIZHA1 minitube[7497]: Creating the database
Jul 19 09:02:17 PATRGRIZHA1 minitube[7497]: Error "Error: Request failed with status code 404"
Jul 19 09:02:17 PATRGRIZHA1 minitube[7497]: "Error: Request failed with status code 404"
Jul 19 09:03:49 PATRGRIZHA1 minitube[7562]: QObject::connect(QWindow, SearchView): invalid nullptr parameter
Jul 19 09:03:50 PATRGRIZHA1 minitube[7562]: Fixing channel ids
Jul 19 09:03:51 PATRGRIZHA1 minitube[7562]: Error "Error: Request failed with status code 404"
Jul 19 09:03:51 PATRGRIZHA1 minitube[7562]: "Error: Request failed with status code 404"
Jul 19 09:03:53 PATRGRIZHA1 minitube[7562]: Error "Error: Request failed with status code 404"
Jul 19 09:03:53 PATRGRIZHA1 minitube[7562]: Error "Error: Request failed with status code 404"
Jul 19 09:03:53 PATRGRIZHA1 minitube[7562]: Error "Error: Request failed with status code 404"
Jul 19 09:03:54 PATRGRIZHA1 minitube[7562]: Error "Error: Request failed with status code 404"
```

When I start minitube from terminal emulator I get this:
```
[pg@PATRGRIZHA1 ~]$ minitube
QObject::connect(QWindow, SearchView): invalid nullptr parameter
Cannot load libcuda.so.1
Error "Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
"Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
```

**Comment by jnbrains** [comment]
I have similar problem, but it's not limited to subscribed videos only.
I'm unable to play any videos in the last two weeks (v3.9 & v3.9.1).

Here are the log messages:

```
$ minitube
Wayland not supported
Cannot load libcuda.so.1
Error "Error: Request failed with status code 404"
"Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
"Error: Request failed with status code 404"
"ReferenceError: trending is not defined"  is not callable
Error "ReferenceError: trending is not defined"
"ReferenceError: trending is not defined"  is not callable
Error "ReferenceError: trending is not defined"
Error "Error: Request failed with status code 404"
"Error: Request failed with status code 404"
Error "Error: Request failed with status code 404"
Error "Error: XHR error"
Error "Error: XHR error"
Error "Error: Request failed with status code 404"
```

It started with (unable to play anything, just skipping to next):
```
Error "Error: XHR error"
```

Then these started showing up later:
```
Error "Error: Request failed with status code 404"
"Error: Request failed with status code 404"
```

Yet, it still is able to fetch/update subscriptions, 
just unable to play any of them, or any other videos.

After I try using minitube, I hit the youtube site via a web browser
and start getting the captchas with suspicious activity warning.

P.S. I'm using ArchLinux (current). minitube is installed from official repo package (3.9.1).

**Comment by alicavus** [comment]
>After I try using minitube, I hit the youtube site via a web browser
and start getting the captchas with suspicious activity warning.

@jnbrains I guess your problem is caused by anti-spam measures of YouTube. If you are connected from work maybe your Network is listed in some [Blocklist IP database](https://whatismyipaddress.com/blacklist-check).

**Comment by jnbrains** [comment]
Not blacklisted (checked with the url provided by you as well).

If I was, by a party not listed in the database, which yt uses,
that would mean that I'll be blocked all the time, and would
affect other devices on my home network, which it does not.

I can view yt via browser without problems for days. Usually,
I get the captcha after 'playing' with minitube.

My though process was that yt 'sees' minitube requests as 
garbled in some manner, and activates the protection.

**Comment by jnbrains** [comment]
Purging the app cache (rm -rf ~/.cache/Flavio\ Tordini) fixed the issue for me.
Search and subscription videos are playable now, and no more 404 & XHR errors.

**Comment by jnbrains** [comment]
Sadly that wasn't the solution. It was working yesterday. Now... purge or no purge:
```
$ minitube
Wayland not supported
Cannot load libcuda.so.1
Error "Error: XHR error"
Error "Error: XHR error"
Error "Error: XHR error"
```
 And keeps jumping to next video without able to play it (search & subscriptions)

**Comment by 414n** [comment]
I have this same issue with all my subscriptions with version 3.9.3.

I can only play videos from either direct searches or from the "Browse" tab.
