### ISSUE TITLE
Icons doesn't show up in "Browse"

### ISSUE THREAD

**Issue by orlandohuang** [flaviotordini/minitube#213]
When I click on the browse tab, only Music shows up at the right bottom. Others don't show up
![image](https://user-images.githubusercontent.com/86908394/141087092-878d5a0a-b6ba-4659-90d0-bab8e5fa1482.png)
<div align="center">
<img src="https://sdk.bitmoji.com/render/panel/02919870-550c-48e9-b644-df89ae03584e-e2a16289-6d3b-4507-b86e-91012043289e-v1.png?transparent=1&palette=1&width=246" alt="Help Bitmoji">
</div>

**Comment by flaviotordini** [comment]
Fixed in 3.9.2

**Comment by orlandohuang** [comment]
Ok tks
