### ISSUE TITLE
Cannot load libcuda.so.1

### ISSUE THREAD

**Issue by olcc** [flaviotordini/minitube#221]
Hello,
I wanted to try minitube, so I installed version 3.9.3 on my Debian system.
The minitube program opens, but I see no search result and no video, and the terminal indicates `Cannot load libcuda.so.1`. 
It is not suitable for me to install this `libcuda1` because it brings all the NVIDIA stuff and modifies tons of things, while I do not have a NVIDIA card on my computer (my graphic card is from INTEL).
Olivier

**Comment by flaviotordini** [comment]
Check wheter MPV works on your system... that's what Minitube uses internally via libmpv.

**Comment by olcc** [comment]
I checked that "mpv" does work on my system (Debian testing). 
Yet, I get no search result from "minitube" (3.9.1) in the "Pick a video" panel.
