### ISSUE TITLE
When installed from source there is no application icon in GNOME

### ISSUE THREAD

**Issue by RustyRaptor** [flaviotordini/minitube#222]
System information:
```
OS: Pop!_OS 22.04 LTS x86_64
Kernel: 5.17.5-76051705-generic
DE: GNOME 42.1 on X11
```
Steps to reproduce:
1. Follow the build and install instructions on the README.md 

I am not sure if this behavior is specific to the source build version. 

![image](https://user-images.githubusercontent.com/7911442/171040120-ec070af0-e70a-45ca-81d8-a60cf42ea837.png)

**Comment by flaviotordini** [comment]
did you "make install"? Anyway I don't think running make install is a good idea. My suggestion is you copy the .desktop file to ~/.local/share/applications and edit the executable path
