### ISSUE TITLE
Flathub.org version out of date

### ISSUE THREAD

**Issue by sysfu** [flaviotordini/minitube#224]
latest release of minitube is currently 3.9.3 Feb 2nd, 2022.

[Flathub version](https://flathub.org/apps/details/org.tordini.flavio.Minitube) is still at 3.7 last updated Dec 30, 2020.

**Comment by flaviotordini** [comment]
It's not mantained by me.

**Comment by sysfu** [comment]
> It's not mantained by me.

Reason I posted here is that I was having difficulty determining who maintained it. When I clicked on the [flathub publisher details link](https://github.com/flathub/org.tordini.flavio.Minitube/graphs/contributors/) I'm not sure which of the four contributors I should contact.
