### ISSUE TITLE
playback buffer (often) every 5 seconds or so

### ISSUE THREAD

**Issue by mrkapqa** [flaviotordini/minitube#225]
Hello Flavio,

on Linux Ubuntu Flavour noticed that lately when using Minitube 
video would play but often buffer every 5 seconds or so;

is there something can do about it?
internet is reasonably fast here.

thank you
grazie.

**Comment by Kieltux** [comment]
Hello, here too. 
And since a few days I can't play any videos anymore: https://github.com/flaviotordini/minitube/issues/226

**Comment by flaviotordini** [comment]
I'm working on it. There's a bug in QJSEngine that's not helping...

**Comment by flaviotordini** [comment]
Should be fixed now. Let me know if you still have this issue.

**Comment by Kieltux** [comment]
Thank you very much. Yes, everything is working.
