### ISSUE TITLE
Error "Error: Can't cut unsupported JSON (no matching closing bracket found)"

### ISSUE THREAD

**Issue by Kieltux** [flaviotordini/minitube#226]
Since a few days minitube 3.9.3 seems to be broken:
Every try to play a video just fails with:
`Error "Error: Can't cut unsupported JSON (no matching closing bracket found)"`

Maybe a change on the invidious site? I found this change: https://github.com/iv-org/invidious/pull/3238#issuecomment-1250119986

Removing the cache directory (~/.cache/Flavio Tordini/Minitube) does not help.

**Comment by flaviotordini** [comment]
Should be fixed by now. Let me know if you still get the error.

**Comment by Kieltux** [comment]
Thank you very much. I can confirm that the problem is gone.
