### ISSUE TITLE
src/aboutview.cpp: compilation error

### ISSUE THREAD

**Issue by CdeMills** [flaviotordini/minitube#249]
Hello
src/aboutview.cpp line 202 reads:
``verticalLayout->addWidget(new AppsWidget());
``

But this generates an error:
src/aboutview.cpp: In constructor 'AboutView::AboutView(QWidget*)':
src/aboutview.cpp:202:46: error: no matching function for call to 'AppsWidget::AppsWidget()'
  202 |     verticalLayout->addWidget(new AppsWidget());
      |                                              ^
In file included from src/aboutview.cpp:33:
lib/qt-reusable-widgets/appwidget.h:29:5: note: candidate: 'AppsWidget::AppsWidget(QWidget*)'
   29 |     AppsWidget(QWidget *parent);
      |     ^~~~~~~~~~
lib/qt-reusable-widgets/appwidget.h:29:5: note:   candidate expects 1 argument, 0 provided
gcc version 11.4.1
It seems that AppsWidget() require a "parent" argument. Any idea ?

gcc version 11.4.1 on Centos Stream 9

TIA

Pascal

**Comment by flaviotordini** [comment]
Thanks fixes, Minitube master is currently in development and will break from time to time.
