### ISSUE TITLE
internal server error?

### ISSUE THREAD

**Issue by mrkapqa** [flaviotordini/minitube#253]
Hello ,

oinstalled today minitube .latest deb on Ubuntu 20.04 but for some reason it would not play?

getting error>

minitube
QObject::connect(QWindow, SearchView): invalid null parameter
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"
Error "Error: Internal Server Error"

thank you,
grazie.

**Comment by ktbloomq** [comment]
same here

**Comment by Panikuz** [comment]
one more with the same problem

**Comment by hawav** [comment]
+1

**Comment by mrkapqa** [comment]
thank you, it function with newer version 4, however.
