### ISSUE TITLE
Videos in search results can be moved around

### ISSUE THREAD

**Issue by vfscanf** [flaviotordini/minitube#28]
Hi,

I noticed that you can reorganize items in the (channel) search results. This behaviour is explicitly enabled in src/playlistview.cpp at line 41:
```
setAcceptDrops(true);
setDropIndicatorShown(true);
setDragDropMode(QAbstractItemView::DragDrop);
```

I don't think that a user should be able to do that. The application doesn't even save the new order (why would it?). I can't think of other applications that allow you to reorganize search results. When I first discovered it, I found it weird and confusing.
My question is: Is there a reason why this is enabled?

**Comment by flaviotordini** [comment]
This is of course useful to customize the playlist and remove uninteresting videos. I use it myself very often. I would say it's a core feature of Minitube.
