### ISSUE TITLE
Minitube under Ubuntu 14.04 is unstable

### ISSUE THREAD

**Issue by lpuzio** [flaviotordini/minitube#31]
I have three issues, since I upgraded from Minitube 2.4 to 2.5.1.

- The main issue is that Minitube is unstable. During playing videos, maximizing / unmaximizing, changing videos it hangs. Unfortunately, it did not report any errors to console. Dmesg also see no problems.
- The second issue is that Minitube takes lots of time to enter Subscription tab after I click it. In version 2.4 it was with no delay.
- The last issue is that some icons in Subscriptions tab are 1/4 of its original size.

I'm using Xubuntu 14.04, with Phonon4QT5 4.7.80, and QT 5.2.1.
Best regards,

**Comment by lpuzio** [comment]
When I run Minitube in terminal it reports many times:
"QWidget::paintEngine: Should no longer be called"
But this is not connected to Minitube hangs.

The second log says:
"** (minitube:2185): CRITICAL **: gst_video_info_from_caps: assertion 'caps != NULL' failed"
It occurs when I change video to play.

**Comment by flaviotordini** [comment]
1 is a phonon-gstreamer bug, I can't do anything about it. I don't know about 2. Opening the subscription tabs should be always fast. No costly operation is done. 3 should fix itself when the thumbs are refreshed.

**Comment by lpuzio** [comment]
Thank you for reply. 
For now I will uninstall minitube, since it is unstable and unusable for Ubuntu.
I'm waiting for new version and I will see if there is no issues, because I liked older version.
Best regards.
