### ISSUE TITLE
does not work correctly without a pulseaudio

### ISSUE THREAD

**Issue by vasisualiy** [flaviotordini/minitube#33]
Install a minitube, that need a phonon-qt5. If I choose phonon-qt5-gstreamer as a bacjend, I get a stocked audio, but no video. If I choose a phonon-qt5-vlc I get an excellent video, but no audio.

The workaround is to remove a libpulse_plugin.so from /usr/lib/vlc/plugins/audio_output.

Or can you take back an mplayer backend? It was perfect and works with a IR remote too.

**Comment by flaviotordini** [comment]
This could be a Phonon backend bug, not a Minitube one.
