### ISSUE TITLE
Remove need for API key

### ISSUE THREAD

**Issue by Natureshadow** [flaviotordini/minitube#34]
NewPipe (https://github.com/theScrabi/NewPipe) seems to be perfectly able to access YouTube without needing an API key.

Please port this access method instead of the current one in Minitube, most importantly because of #17, but also because it is generally a good idea to have that dependency removed.

**Comment by sergiomb2** [comment]
I'd like suggest that at least GOOGLE_API_KEY should be configurable in a minitube conf file, if no key are configured minitube should ask for it, IMHO, not at compile time .

**Comment by logos88** [comment]
This would be a good privacy improvement too

**Comment by XorgMC** [comment]
NewPipe does not use the YouTube API to access data. Minitube would need a huge rewrite to archive this. Also the API exists for a reason - if YouTube changes their website structure/layout/etc., it may break everything!

**Comment by sergiomb2** [comment]
At least we need set API key by user and not by packager , packages are meant to be distribute for all kind of situations, doesn't make sense packager set the API key , when don't know where will be used.

**Comment by moshpirit** [comment]
WebTube (another Android client) also allows us to use it under tor while doesn't accept cookies, so we do have even more privacy ;)

**Comment by sergiomb2** [comment]
fuck flaviotordini , we removed minitube from RPMFusion .

**Comment by Aqa-Ib** [comment]
You can "export GOOGLE_API_KEY=you_key_here" and it will work, no need to recompile.

**Comment by ntassani** [comment]
i dont know how to put my api key... And if i compile minitube jump between thumbnails and cant play anithing...
