### ISSUE TITLE
Phonon backend plugin could not be loaded.

### ISSUE THREAD

**Issue by DebianVaio** [flaviotordini/minitube#35]
Hi. I built Minitube 2.5.2 in Ubuntu 14.04 smoothly, but does not play any video. This is the message from the terminal. How can I solve that. Thanks.

$ minitube
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: Phonon::createPath: Cannot connect Phonon::MediaObject ( no objectName ) to Phonon::AudioOutput ( no objectName ).
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded
WARNING: Phonon::createPath: Cannot connect Phonon::MediaObject ( no objectName ) to Phonon::VideoWidget ( no objectName ).

Thank you.

**Comment by flaviotordini** [comment]
Maybe install a Phonon backend?

**Comment by DebianVaio** [comment]
I have installed phonon, phonon-backend-vlc, phonon4qt5-backend-null, libphonon4, libphonon4qt5-4, python-qt4, libphonon4qt5-dev. What else do I need? Thanks.

**Comment by flaviotordini** [comment]
You should ask this in your distribution support forum
