### ISSUE TITLE
error compiling for Fedora 23 

### ISSUE THREAD

**Issue by sergiomb2** [flaviotordini/minitube#36]
g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -DAPP_VERSION=2.5.2 -DAPP_NAME=Minitube -DAPP_UNIX_NAME=minitube -DAPP_PHONON -DAPP_PHONON_SEEK -DAPP_SNAPSHOT -DAPP_YT3 -DQT_NO_DEBUG_OUTPUT -DQT_USE_QSTRINGBUILDER -DQT_STRICT_ITERATORS -DAPP_LINUX -DDATADIR=\"/usr/share\" -DPKGDATADIR=\"/usr/share/minitube\" -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_DBUS_LIB -DQT_SCRIPT_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtSql -I/usr/include/QtScript -I/usr/include/QtDBus -I/usr/include/phonon -I/usr/include -Ilocale -I/usr/include/QtSolutions -I/usr/include/phonon_compat -Ibuild/moc -o build/obj/video.o src/video.cpp
src/main.cpp: In function 'int main(int, char**)':
src/main.cpp:86:22: error: 'AA_UseHighDpiPixmaps' is not a member of 'Qt'
     app.setAttribute(Qt::AA_UseHighDpiPixmaps);
                      ^
src/video.cpp: In member function 'void Video::setThumbnail(const QByteArray&)':
src/video.cpp:99:80: error: 'class QApplication' has no member named 'devicePixelRatio'
src/video.cpp:102:17: error: 'class QPixmap' has no member named 'setDevicePixelRatio'
     m_thumbnail.setDevicePixelRatio(ratio);
                 ^
Makefile:969: recipe for target 'build/obj/video.o' failed
make: *** [build/obj/video.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:950: recipe for target 'build/obj/main.o' failed
make: *** [build/obj/main.o] Error 1

**Comment by kkofler** [comment]
Looks like you need to build this with Qt 5 rather than 4 now.

**Comment by sergiomb2** [comment]
yeah , 
-BuildRequires:  qt4-devel
-BuildRequires:  phonon-devel
-BuildRequires:  qtsingleapplication-devel

+BuildRequires:  qt5-qtbase-devel
+BuildRequires:  qtsingleapplication-qt5-devel
+BuildRequires:  phonon-qt5-devel
+BuildRequires:  qt5-qtscript-devel
+BuildRequires:  qt5-linguist

fixed the problem , thanks for the tip ! .
