### ISSUE TITLE
Channel names not displayed

### ISSUE THREAD

**Issue by Grarap** [flaviotordini/minitube#4]
I am not sure yet why or when it happens, but depending on the search term, some or many search results will not display the channel's name which also makes it impossible to subscribe to them.

At first I thought it happened with channels that had a space in their name but it also happens with channels which don't (e.g. the channel VeganRevolution).

**Comment by flaviotordini** [comment]
Yes, I'm aware of this. Channel names are sometimes missing in the API response so it's not a Minitube bug but rather a YouTube API v3 bug.

**Comment by flaviotordini** [comment]
I think I'll leave this open until YouTube fixes itself.

**Comment by Grarap** [comment]
In the last comment in this bug report, there is a workaround mentioned, but I'd understand if you don't want to introduce workaround code into your application:
https://code.google.com/p/gdata-issues/issues/detail?id=6104
