### ISSUE TITLE
Does Minitube delete the cookies?

### ISSUE THREAD

**Issue by moshpirit** [flaviotordini/minitube#41]
I'd like to delete the cookies of Youtube. Does Minitube already do that? if not, could you create an option to delete the cookies every time we close Minitube or just to not accepting them?

**Comment by flaviotordini** [comment]
No cookies are involved when you use Minitube.

**Comment by moshpirit** [comment]
Cool, thanks for the answer! So what information get YouTube from me?

**Comment by flaviotordini** [comment]
Just your IP address, I suppose.

**Comment by moshpirit** [comment]
Cool! thank you!
