### ISSUE TITLE
Google api: forbidden when searching

### ISSUE THREAD

**Issue by luispabon** [flaviotordini/minitube#49]
![image](https://cloud.githubusercontent.com/assets/6388823/16724037/7a9d976a-4748-11e6-9f0b-7139c4b916b6.png)

**Comment by flaviotordini** [comment]
You have to report that to the Ubuntu devs. They (or Debian) built Minitube without a Google API key.

**Comment by luispabon** [comment]
This is a minitube bug though, you don't distribute API keys with applications, you make applications able to acquire them as needed.
