### ISSUE TITLE
Only 360p in Videos

### ISSUE THREAD

**Issue by Teyro** [flaviotordini/minitube#50]
Hi there,

Since 2-3 months i only can watch videos in 360p .... It is very confoseing... Becuase if i use the native YouTube Site i will get 1080p.... I cant click on the Button on the main page to change to 720p or more...? What is happening?

**Comment by Teyro** [comment]
no one can help me :S Makes me sad, because i need to use youtube native.... :(

**Comment by flaviotordini** [comment]
Why can't you click on the resolution button? It should be always enabled when you're in the search view.
