### ISSUE TITLE
Build on macOS

### ISSUE THREAD

**Issue by darvelo** [flaviotordini/minitube#57]
Hi Flavio! Thanks so much for your work on Minitube. I've had many great days relaxing and watching videos with it on Linux.

Now that I have a Mac I'd like to be able to build it on macOS, primarily for using my own API key, but also potentially adding the odd fix once in a while in between releases. Is this possible?

**Comment by flaviotordini** [comment]
Building on Mac is not supported. I do a proprietary build for Mac that you can buy on my site.
