### ISSUE TITLE
Video always on top...

### ISSUE THREAD

**Issue by bobblkabb** [flaviotordini/minitube#58]
on every Desktop
Didn't have this behaviour on my old computer. My new one (LG 34" widescreen with big ass resolution) is showing the video on every workspace always on top. Pretty annoying. 
Linux Mint 18.

**Comment by flaviotordini** [comment]
Which Phonon backend are you using? Are you using the package from my site?

**Comment by bobblkabb** [comment]
phonon4qt5-backend-gstreamer:amd64
4:4.8.2-0ubuntu2
Phonon Qt5 GStreamer 1.0 backend

**Comment by flaviotordini** [comment]
Your Phonon backend is somehow broken. This has nothing to do with Minitube. Try changing it or report the bug to your distro.
