### ISSUE TITLE
channel starts video automatically

### ISSUE THREAD

**Issue by bobblkabb** [flaviotordini/minitube#59]
Couldn't find a setting to change and as far as I remember it used to be different on my old desktop machine.
Sometimes the video starts but doesn't play, it's stuck. Got to push the stop button and re-enter the channel again. 
Linux Mint 18

**Comment by PorscheLauren** [comment]
sounds like a back-end problem to me., its phonom-vlc.  
When it comes to codec nothing free is good.

Mint has it own codec packages. I would check their documentation first.

**Comment by flaviotordini** [comment]
Videos start automatically unless you check Playback -> Manually start playing
