### ISSUE TITLE
Can't scale video

### ISSUE THREAD

**Issue by bobblkabb** [flaviotordini/minitube#60]
As I mentioned on an earlier bug report I've got a new pretty large screen (LG 34") and I can't toggle the picture to full screen. It's always quite tiny even at the highest resolution.
Linux Mint 18

**Comment by flaviotordini** [comment]
Looks like the Phonon backend you are using is malfunctioning. This is not a bug with Minitube. Try changing to a different backend or seek support on your distro forums.
