### ISSUE TITLE
2.6 doesn't start

### ISSUE THREAD

**Issue by bobblkabb** [flaviotordini/minitube#61]
Getting following error message:
`minitube: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: no version information available (required by minitube)
minitube: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: no version information available (required by minitube)
minitube: relocation error: minitube: symbol _ZNK18QAbstractListModel7siblingEiiRK11QModelIndex, version Qt_5 not defined in file libQt5Core.so.5 with link time reference`

Linux Mint 17.3, 64Bit

**Comment by flaviotordini** [comment]
I built the package on Ubuntu 16.10 and probably you have older Qt libs. I'll rebuild it on 16.04 LTS as I usually build on the latest Ubuntu LTS.

**Comment by flaviotordini** [comment]
Rebuilt deb on Ubuntu 16.04. Download again.

**Comment by bobblkabb** [comment]
Something's still off, doesn't start:
`minitube: symbol lookup error: minitube: undefined symbol: _ZNK18QAbstractListModel7siblingEiiRK11QModelIndex`

**Comment by flaviotordini** [comment]
You don't state your distro and Qt version. Anyway my package cannot work on all distro versions. If you have older Qt libraries build by yourself or wait for your distro to provide a package.

**Comment by bobblkabb** [comment]
Linux Mint 17.3, 64Bit
There are qt4 and qt5 packages installed. The main versions: 4.8.5 and 5.2.1
Does this help? Do you need more precise information?
