### ISSUE TITLE
2.6 build failure

### ISSUE THREAD

**Issue by antonio-rojas** [flaviotordini/minitube#62]
Using Qt 5.8, GCC 6.3.1

src/yt3.cpp: In constructor 'YT3::YT3()':
src/yt3.cpp:52:41: error: 'class QCoreApplication' has no member named 'activeWindow'
         QMetaObject::invokeMethod(qApp->activeWindow(), "missingKeyWarning");
                                         ^~~~~~~~~~~~
make: *** [Makefile:2066: build/obj/yt3.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by flaviotordini** [comment]
Thanks for the report! It should be ok now. I've updated the 2.6 tag.
