### ISSUE TITLE
Minitube 2.6 videos not always playing - (phonon is properly installed)

### ISSUE THREAD

**Issue by aproposnix** [flaviotordini/minitube#64]
Since upgrading to minitube 2.6 I've had a lot of issues with videos not playing. It's not happening with every video but I'd say at least half of the videos on my channels don't play. Also, if a video doesn't play, I can come back to it later (meaning a shutdown of minitube and restart later in the day) and often it will play.  

As I thought it might be an API key issues, I went ahead and generated my own API key and compiled minitube from the latest source on Github... same result.  Some videos play, others do not. 

Is there anything I can do to track down the problem?  I was looking for logs for minitube but couldn't find any.  

I'm on Ubuntu 16.04. Phonon is installed correctly (it worked fine on the previous build for example).

**Comment by flaviotordini** [comment]
This should be fixed by now
