### ISSUE TITLE
How to debug black playback window?

### ISSUE THREAD

**Issue by probonopd** [flaviotordini/minitube#65]
I am [trying to build](https://github.com/probonopd/minitube/blob/patch-1/.travis.yml) Minitube on [Travis CI](https://travis-ci.org/) and package it as an [AppImage](http://appimage.org/), along with Phonon, libvlc and its plugins.

The build succeeds, the app launches, I can successfully search Google, but the playback window stays black.

The AppImage is _not_ supposed to use Phonon or VLC from the system, so I am on my own here. Can you give me some hints on how to debug this?

https://transfer.sh/RJmrp/minitube-git.50a9739-x86-64.appimage

---

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by flaviotordini** [comment]
Try setting the env variable PHONON_DEBUG=1

**Comment by probonopd** [comment]
Unfortunately this is all output I get:

```
me@host:~$ export  PHONON_DEBUG=1
me@host:~$ /home/me/Downloads/Minitube-git.5ba52bc-x86_64.AppImage 
QIODevice::read (QFile, ":/functions.js"): device not open
Cannot write "No such file or directory" "/home/me/.local/share/Flavio Tordini/Minitube/functions.js"
```

**Comment by flaviotordini** [comment]
This is already fixed in git. 2.7 is going to be released very soon.
