### ISSUE TITLE
Some Videos or subscriptions are not playing

### ISSUE THREAD

**Issue by lucasmenezesds** [flaviotordini/minitube#66]
Some videos load the description, it seems that will beging to play but it doesn't

**Terminal log shows:**
```
Error in 
"f('DC7EB0B5EE5722C8A10AEBA355A71CE273FD3A35.01E9FE3CD9DD20A2AD812EAFB648015F9A62F4AC');" "ReferenceError: l is not defined"

```

**Every time that some video don't play it appers:**

`"f('some.key');" "ReferenceError: l is not defined"`

Some channels all the videos play, others just some videos play and others none of it starts.

OBS: I re imported the API KEY and built it again
This Issue is related with issue #64

**Comment by deesklo** [comment]
This error occurs if Youtube sends js containing a piece like the following:
`gy=function(a,b,c){for(var d=[],e=0;e<b.length;e++){var f=b[e];if(f.url){var k=new Fv(f.url);f.sig?k.set("signature",f.sig):f.s&&k.set("signature",wc(f.s));for(var l in c)k.set(l,c[l]);f=Um(f.type,f.quality,f.itag,f.width,f.height,!!f.isAccelerated,!!f.isAcceleratedUiEnabled);d.push(new fy(f,k))}}return Zu(a.M,d)};`

The first occurrence of `"signature"` is then being matched by the regex `funcNameRe` [here](https://github.com/flaviotordini/minitube/blob/2.6/src/video.cpp#L359), and `f` is recognized as the function name. But `f` in that piece is not a function name at all. Maybe the regex should contain an opening bracket to ensure it captures a function name? Like this:

`function signatureFunctionNameRE() {
    return "\"signature\"\\s*,\\s*([%1]+)\(";
}`

**Comment by thewolfwillcome** [comment]
@deesklo:
Your suggestion works with a tiny modification:
`function signatureFunctionNameRE() { return "\"signature\"\\s*,\\s*([%1]+)\**\**("; }`
We need "\\(" instead of "\(" so that "\(" gets feeded into the regex instead of only "("

**Comment by flaviotordini** [comment]
Fixed this yesterday. Unfortunately i didn't read the report and the proposed fix before. Great job everybody.

**Comment by lucasmenezesds** [comment]
That's awesome! Thank you very much @deesklo , @thewolfwillcome  and  @flaviotordini  For all the help and the fix!
