### ISSUE TITLE
Help with api key (please)

### ISSUE THREAD

**Issue by ntassani** [flaviotordini/minitube#70]
I dont know how to put my api key... And if i compile minitube jump between thumbnails and cant play anithing...

**Comment by lucasmenezesds** [comment]
Did you tried follow this steps?

[https://github.com/flaviotordini/minitube#build-instructions](https://github.com/flaviotordini/minitube#build-instructions)
 or

[http://askubuntu.com/posts/672505/revisions](http://askubuntu.com/posts/672505/revisions)

**Comment by syl3nt** [comment]
well, i built with aur, so i can't make it that way, how can i access the variable and introduce apikey there ?

**Comment by flaviotordini** [comment]
https://github.com/flaviotordini/minitube#google-api-key

**Comment by mrkapqa** [comment]
me too is having these problems,

i created key for

 YouTube Data API v3 

is this "BrowserKey"? sadly, the videos show up in search bar, but wont play

**Comment by mrkapqa** [comment]
No available API keys
403 "Error transferring https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&q=love all - server replied: Forbidden" QNetworkReply::NetworkError(ContentOperationNotPermittedError)
"Error transferring https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=50&q=love all - server replied: Forbidden"

**Comment by mrkapqa** [comment]
![bildschirmfoto zu 2017-11-25_22-37-40](https://user-images.githubusercontent.com/12947465/33235078-5742036c-d231-11e7-9453-9b5777824f67.png)
