### ISSUE TITLE
No playback / Lubuntu 16.04 64bit

### ISSUE THREAD

**Issue by pi99y** [flaviotordini/minitube#71]
Hi!
I installed the .deb (minitube v2.6) from your website and when I start Minitube:
+ searching works fine
+ videos are displayed with thumbnails
+ video description is shown

but:
- they don't play (no audio / video)

I tried:
+ other Minitube versions / repository
+ I tried your suggestion of removing phonon-backend* but this removes minitube tool
+ I tried adding *gstreamer-vlc

Please help me solve it. Thank you!

**Comment by steave-r0gers** [comment]
try yo install phonon4qt5-backend-vlc and delete phonon4qt5-backend-null

**Comment by pi99y** [comment]
Hi @steave-r0gers, thank you for responding.
If I try to install phonon4qt5-backend-vlc it indicates that minitube will be removed while phonon4qt5-backend-null is not (yet) installed on my system.
Any ideas?
Thank you!

**Comment by flaviotordini** [comment]
Phonon backend issues don't belong here. Try installing Gstreamer plugins, bad and ugly.
