### ISSUE TITLE
functions.js not found

### ISSUE THREAD

**Issue by diogo-gomes** [flaviotordini/minitube#72]
When I try to play a video on minitube, I get:

`Cannot write "No such file or directory" "/home/myusername/.local/share/Flavio Tordini/Minitube/functions.js`

I'm using Manjaro and I get same error when installed from AUR and when compiled from source.

**Comment by jensMF** [comment]
I have the same issue under Ubuntu 16.04. I build it myself.

**Comment by mtl0612** [comment]
I also ran to the same problem.
Fixed it by created "~/.local/share/Flavio Tordini/Minitube" folder

**Comment by flaviotordini** [comment]
Thanks guys, this is fixed now for version 2.7
