### ISSUE TITLE
WARNING: bool Phonon::FactoryPrivate::createBackend() phonon backend plugin could not be loaded

### ISSUE THREAD

**Issue by Slec70** [flaviotordini/minitube#85]
Hi Flavio,
Finished the minitube's compilation I can not play anything of the playlist after search. So running the minitube with build/target/minitube I noticed the error message of subtitle, so after some searching I found a solution, just install the phonon4qt5 phonon4qt5-backend-gstreamer phonon4qt5-backend-vlc.
Could you add those ones in the build instructions?
Thanks&Regards,

**Comment by flaviotordini** [comment]
The readme has a "disclaimer" about Phonon setup. Distros vary, so it is better to refer to each distro documentation.
