### ISSUE TITLE
Can't change API key and doesn't work from env

### ISSUE THREAD

**Issue by muesli4** [flaviotordini/minitube#89]
I installed *minitube* as Archlinux package. Ergo no YouTube API key. Consequently, the application prompted me for the API key. I generated it and entered it. Then I noticed that there is a single space character at the beginning of the url, which is probably due to copying it out of the browser. However there is no way to change it again, there are no settings and I can't find a configuration file in any sensible directory. (Why is that?)

Then I tried it with the environment variable version. Now it doesn't use the key anymore and I get a 403 http return code.

edit: Found it under **~/.config/Flavio Tordini/Minitube.conf**.

**Comment by flaviotordini** [comment]
Yes it's in ~/.config/Flavio Tordini/Minitube.conf (that's generated by QSettings so complain to Qt ;)
