### ISSUE TITLE
[Feature Request] Night Mode

### ISSUE THREAD

**Issue by ferlanero** [flaviotordini/minitube#93]
Minitube is, after 2.9 release, almost perfect. I'm using it on Manjaro, ArchLinux  & Ubuntu Budgie 17.10 everything compiled form source and I must to admit that I prefer viewing Youtube through Minitube 2.9 than the native Youtube web.

The only thing I miss on this fantastic program is a night mode which darkening the ui in low light condition.

Flavio, do you think it would be possible?

At any way, thank you very much for making Minitube a piece of gold!

**Comment by flaviotordini** [comment]
Minitube now adapts dynamically to a theme change. Did this for macOS Mojave. Only problem in Linux is a GTK theme change is probably not picked on the fly by Qt.
